/**
 * ⚒️ La Forja de Hefestos — Machine Configuration Parser
 * ========================================================
 * Parses Fusion 360 .mch files (JSON) into typed TypeScript structures.
 * Supports: CNC milling (3/4/5-axis), turning, additive (FFF/FDM).
 *
 * Based on analysis of 8 real Fusion 360 machine configs:
 *   - Bambu Lab P1P (additive FFF)
 *   - Brother SPEEDIO M300X3 (5-axis mill+turn)
 *   - DATRON neo (3-axis)
 *   - GROB G350 (5-axis)
 *   - HAAS EC-630 (4-axis horizontal)
 *   - HAAS VF-2 (3-axis)
 *   - HAAS VS-3 (3-axis)
 *   - Hurco BX40i (3-axis)
 */

// ═══════════════════════════════════════════════════════════════
// Core Types
// ═══════════════════════════════════════════════════════════════

export type MachineCapability = 'milling' | 'turning' | 'additive';
export type AxisType = 'linear' | 'rotary' | 'static';
export type FeedMethod = 'FPM' | 'inverse time';

export interface MachineAxis {
  name: string;
  coordinate: number;
  maxNormalSpeed: number;
  maxRapidSpeed: number;
  tcp: boolean;
  preference: string;
  wrapAroundMin?: number;
  wrapAroundMax?: number;
}

export interface MachineSpindle {
  maxSpeed: number;
  peakTorque?: number;
  peakTorqueSpeed?: number;
  power?: number;
  coolants?: string[];
}

export interface KinematicNode {
  id: string;
  type: AxisType;
  direction?: [number, number, number];
  rotationAxis?: [number, number, number];
  rangeMin?: number;
  rangeMax?: number;
  home?: number;
  offset?: [number, number, number];
  role?: 'head' | 'table' | 'spindle' | 'tool' | string;
  spindle?: MachineSpindle;
  children: KinematicNode[];
}

export interface MachineController {
  configName: string; // 'default' or 'synced_configuration'
  axes: MachineAxis[];
  headPartId?: string;
  tablePartId?: string;
  tcpRapidMode?: string;
  maxNormalSpeed?: number;
}

export interface MachineMachining {
  feedrateRatio: number;
  toolChangeTime: number;
}

export interface MachineTooling {
  hasToolChanger: boolean;
  numberOfTools: number;
  supportsToolPreload: boolean;
}

export interface MachineMultiaxis {
  singularityAdjust: boolean;
  singularityMethod?: string;
  singularityTolerance?: number;
  feedMethod?: FeedMethod;
  maxFeedrate?: number;
  virtualToolTip: boolean;
  linearizationTolerance?: number;
  retractAndReconfigure?: boolean;
}

export interface MachinePost {
  path: string;
  properties?: Record<string, unknown>;
}

export interface MachineFusion {
  guid?: string;
  image?: string; // base64 PNG
  modelUrn?: string;
  imageAutoGenerated?: boolean;
}

export interface MachineConnection {
  ip: string;
  port: number;
  connectorPath?: string;
  connectorIdent?: string;
}

// ── Additive-specific ──

export interface AdditiveExtruder {
  index: number;
  diameter: number;
  filamentDiameter: number;
  maxTemperature: number;
  maxVolumePerSec: number;
}

export interface AdditiveLimits {
  accelXYMax: number;
  accelZMax: number;
  speedXYMax: number;
  speedZMax: number;
  bedTempMax: number;
}

export interface AdditivePlatform {
  size: [number, number, number]; // [X, Y, Z] in mm
  origin: [number, number, number];
}

// ═══════════════════════════════════════════════════════════════
// Main Machine Config
// ═══════════════════════════════════════════════════════════════

export interface MachineConfig {
  id: string;           // generated UUID
  fileName: string;     // original filename
  vendor: string;
  model: string;
  description: string;
  capabilities: MachineCapability[];

  // CNC sections (present when capabilities includes 'milling' or 'turning')
  controller?: MachineController;
  kinematics?: KinematicNode[];
  machining?: MachineMachining;
  tooling?: MachineTooling;
  multiaxis?: MachineMultiaxis;
  post?: MachinePost;
  connection?: MachineConnection;

  // Additive sections (present when capabilities includes 'additive')
  additiveTechnology?: string;
  extruders?: AdditiveExtruder[];
  limits?: AdditiveLimits;
  platform?: AdditivePlatform;

  // Fusion metadata
  fusion?: MachineFusion;

  // Interaction pairs count (for collision checking)
  interactionPairs?: number;

  // Computed summaries
  axisCount: number;
  maxSpindleSpeed: number;
  workEnvelope: { x: number; y: number; z: number };
}

// ═══════════════════════════════════════════════════════════════
// Parser
// ═══════════════════════════════════════════════════════════════

let _machineIdCounter = 0;

function generateMachineId(): string {
  return `mch_${Date.now()}_${++_machineIdCounter}`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseController(raw: any): MachineController | undefined {
  if (!raw) return undefined;

  // Controllers can be under 'default' or 'synced_configuration'
  const configName = raw.default ? 'default' : raw.synced_configuration ? 'synced_configuration' : Object.keys(raw)[0];
  const config = raw[configName];
  if (!config) return undefined;

  const axes: MachineAxis[] = [];

  // Parts contain axes
  if (config.parts) {
    for (const [name, part] of Object.entries(config.parts)) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const p = part as any;
      axes.push({
        name,
        coordinate: p.coordinate ?? 0,
        maxNormalSpeed: p.max_normal_speed ?? 0,
        maxRapidSpeed: p.max_rapid_speed ?? 0,
        tcp: p.tcp ?? false,
        preference: p.preference ?? 'no preference',
        wrapAroundMin: p.wrap_around_at_min,
        wrapAroundMax: p.wrap_around_at_max,
      });
    }
  }

  return {
    configName,
    axes,
    headPartId: config.head_info_part_id,
    tablePartId: config.table_part_id,
    tcpRapidMode: config.tcp_rapid_interpolation_mode,
    maxNormalSpeed: config.max_normal_speed,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseKinematics(raw: any): KinematicNode[] {
  if (!raw) return [];

  // Actual Fusion 360 structure: raw.default.parts = flat array of part nodes
  const kinDef = raw.default ?? raw;
  const rawParts: unknown[] = kinDef.parts;
  if (!Array.isArray(rawParts)) return [];

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function parseNode(p: any): KinematicNode {
    const node: KinematicNode = {
      id: p.name ?? p.id ?? 'unknown',
      // 'driven' = motorized axis. is_rotational flag distinguishes rotary vs linear.
      type: p.control === 'driven'
        ? (p.is_rotational ? 'rotary' : 'linear')
        : (p.type ?? 'static'),
      children: [],
    };

    if (p.direction) node.direction = p.direction as [number, number, number];
    if (p.min !== undefined) node.rangeMin = p.min;
    if (p.max !== undefined) node.rangeMax = p.max;
    if (p.home !== undefined) node.home = p.home;

    // Spindle / head detection
    if (p.spindle) {
      node.role = 'head';
      node.spindle = {
        maxSpeed: p.spindle.max_speed ?? 0,
        peakTorque: p.spindle.peak_torque,
        peakTorqueSpeed: p.spindle.peak_torque_speed,
        power: p.spindle.power,
        coolants: p.tool_station?.coolants
          ? Object.keys(p.tool_station.coolants)
          : undefined,
      };
    } else if (p.table_station !== undefined) {
      node.role = 'table';
    }

    // Recurse into nested parts array
    if (Array.isArray(p.parts)) {
      for (const child of p.parts) {
        node.children.push(parseNode(child));
      }
    }

    return node;
  }

  return rawParts.map(parseNode);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseMachining(raw: any): MachineMachining | undefined {
  if (!raw) return undefined;
  const cfg = raw.default || raw;
  return {
    feedrateRatio: cfg.feedrate_ratio ?? 1,
    toolChangeTime: cfg.tool_change_time ?? 15,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseTooling(raw: any): MachineTooling | undefined {
  if (!raw) return undefined;
  const cfg = raw.default || raw;
  return {
    hasToolChanger: cfg.has_tool_changer ?? false,
    numberOfTools: cfg.number_of_tools ?? 0,
    supportsToolPreload: cfg.supports_tool_preload ?? false,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseMultiaxis(raw: any): MachineMultiaxis | undefined {
  if (!raw) return undefined;
  const cfg = raw.default || raw;
  return {
    singularityAdjust: cfg.singularity?.adjust ?? false,
    singularityMethod: cfg.singularity?.method,
    singularityTolerance: cfg.singularity?.tolerance,
    feedMethod: cfg.feedrate?.method,
    maxFeedrate: cfg.feedrate?.max_feedrate,
    virtualToolTip: cfg.virtual_tool_tip ?? false,
    linearizationTolerance: cfg.linearization_tolerance,
    retractAndReconfigure: cfg.retract_and_reconfigure?.enabled,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parsePost(raw: any): MachinePost | undefined {
  if (!raw) return undefined;
  const cfg = raw.default || raw;
  const result: MachinePost = {
    path: cfg.path ?? '',
  };
  if (cfg.properties && Object.keys(cfg.properties).length > 0) {
    result.properties = cfg.properties;
  }
  return result;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseFusion(raw: any): MachineFusion | undefined {
  if (!raw) return undefined;
  return {
    guid: raw.guid,
    image: raw.image,
    modelUrn: raw.model_urn,
    imageAutoGenerated: raw.imageAutoGenerated,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseConnection(rawConn: any, rawConnector: any): MachineConnection | undefined {
  if (!rawConn && !rawConnector) return undefined;
  const conn = rawConn?.default?.ethernet ?? {};
  const connector = rawConnector?.default ?? {};
  return {
    ip: connector.ip ?? conn.ip ?? '',
    port: conn.port ?? connector.port ?? 0,
    connectorPath: connector.path,
    connectorIdent: connector.ident,
  };
}

// Compute work envelope from kinematics
function computeWorkEnvelope(kinematics: KinematicNode[]): { x: number; y: number; z: number } {
  const envelope = { x: 0, y: 0, z: 0 };

  const walk = (nodes: KinematicNode[]) => {
    for (const node of nodes) {
      if (node.type === 'linear' && node.rangeMin !== undefined && node.rangeMax !== undefined) {
        const travel = Math.abs(node.rangeMax - node.rangeMin);
        const dir = node.direction;
        if (dir) {
          if (Math.abs(dir[0]) > 0.5) envelope.x = Math.max(envelope.x, travel);
          else if (Math.abs(dir[1]) > 0.5) envelope.y = Math.max(envelope.y, travel);
          else if (Math.abs(dir[2]) > 0.5) envelope.z = Math.max(envelope.z, travel);
        }
      }
      walk(node.children);
    }
  };

  walk(kinematics);
  return envelope;
}

// Find max spindle speed from kinematics tree
function findMaxSpindleSpeed(kinematics: KinematicNode[]): number {
  let max = 0;
  const walk = (nodes: KinematicNode[]) => {
    for (const node of nodes) {
      if (node.spindle && node.spindle.maxSpeed > max) {
        max = node.spindle.maxSpeed;
      }
      walk(node.children);
    }
  };
  walk(kinematics);
  return max;
}

// ═══════════════════════════════════════════════════════════════
// Public API
// ═══════════════════════════════════════════════════════════════

/**
 * Parse a Fusion 360 .mch file (JSON string) into a MachineConfig.
 */
export function parseMachineConfig(json: string, fileName: string = 'unknown.mch'): MachineConfig {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const raw: any = JSON.parse(json);

  const general = raw.general?.default ?? raw.general ?? {};
  const capabilities: MachineCapability[] = (general.capabilities ?? []) as MachineCapability[];

  const controller = parseController(raw.controller);
  const kinematics = parseKinematics(raw.kinematics);
  const machining = parseMachining(raw.machining);
  const tooling = parseTooling(raw.tooling);
  const multiaxis = parseMultiaxis(raw.multiaxis);
  const post = parsePost(raw.post);
  const fusion = parseFusion(raw.fusion);
  const connection = parseConnection(raw.connection, raw.connector);

  // Additive
  let additiveTechnology: string | undefined;
  let extruders: AdditiveExtruder[] | undefined;
  let limits: AdditiveLimits | undefined;
  let platform: AdditivePlatform | undefined;

  if (raw.additive) {
    const addDefault = raw.additive.default ?? raw.additive;
    additiveTechnology = addDefault.technology;
  }

  if (raw.additive_extruder) {
    extruders = [];
    for (const [key, val] of Object.entries(raw.additive_extruder)) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ext = val as any;
      extruders.push({
        index: parseInt(key) || 0,
        diameter: ext.diameter ?? 0.4,
        filamentDiameter: ext.filament_diameter ?? 1.75,
        maxTemperature: ext.max_temperature ?? 260,
        maxVolumePerSec: ext.max_volume_per_sec ?? 15,
      });
    }
  }

  if (raw.limits?.default) {
    const lim = raw.limits.default;
    limits = {
      accelXYMax: lim.accel_xy_max ?? 0,
      accelZMax: lim.accel_z_max ?? 0,
      speedXYMax: lim.speed_xy_max ?? 0,
      speedZMax: lim.speed_z_max ?? 0,
      bedTempMax: lim.bed_temp_max ?? 0,
    };
  }

  if (raw.platform?.default?.dimensions) {
    const dim = raw.platform.default.dimensions;
    platform = {
      size: dim.size ?? [200, 200, 200],
      origin: dim.origin ?? [0, 0, 0],
    };
  }

  // Compute summaries
  const axisCount = controller?.axes.length ?? 0;
  const maxSpindleSpeed = findMaxSpindleSpeed(kinematics);
  const workEnvelope = capabilities.includes('additive') && platform
    ? { x: platform.size[0], y: platform.size[1], z: platform.size[2] }
    : computeWorkEnvelope(kinematics);

  // Interaction pairs count
  let interactionPairs: number | undefined;
  if (raw.interactions?.default) {
    interactionPairs = Object.keys(raw.interactions.default).length;
  }

  return {
    id: generateMachineId(),
    fileName,
    vendor: general.vendor ?? 'Unknown',
    model: general.model ?? 'Unknown',
    description: general.description ?? '',
    capabilities,
    controller,
    kinematics,
    machining,
    tooling,
    multiaxis,
    post,
    connection,
    fusion,
    additiveTechnology,
    extruders,
    limits,
    platform,
    interactionPairs,
    axisCount,
    maxSpindleSpeed,
    workEnvelope,
  };
}

/**
 * Import a .mch file from a File object.
 */
export async function importMachineFile(file: File): Promise<MachineConfig> {
  const text = await file.text();
  return parseMachineConfig(text, file.name);
}

/**
 * Get a short display string for a machine
 */
export function machineDisplayString(m: MachineConfig): string {
  const caps = m.capabilities.join('+');
  const axes = m.axisCount > 0 ? `${m.axisCount}-axis` : '';
  const envelope = m.workEnvelope.x > 0
    ? `${m.workEnvelope.x}×${m.workEnvelope.y}×${m.workEnvelope.z}mm`
    : '';

  return [m.vendor, m.model, `(${caps}${axes ? ' ' + axes : ''})`, envelope]
    .filter(Boolean)
    .join(' ');
}

/**
 * Get machine type icon for UI display
 */
export function machineIcon(m: MachineConfig): string {
  if (m.capabilities.includes('additive')) return '🖨';
  if (m.capabilities.includes('turning')) return '🔄';
  if (m.axisCount >= 5) return '⚙️';
  if (m.axisCount >= 4) return '🔧';
  return '🏭';
}

/**
 * Get envelope as formatted string
 */
export function formatEnvelope(m: MachineConfig): string {
  const { x, y, z } = m.workEnvelope;
  if (x === 0 && y === 0 && z === 0) return 'N/A';
  return `${x} × ${y} × ${z} mm`;
}

/**
 * Get all machine attributes as omnibar-searchable entries
 */
export function machineSearchEntries(machines: MachineConfig[]): {
  id: string;
  label: string;
  description: string;
  category: string;
  icon: string;
  machine: MachineConfig;
}[] {
  return machines.map(m => ({
    id: m.id,
    label: `${m.vendor} ${m.model}`,
    description: `${m.capabilities.join(', ')} · ${m.axisCount} ejes · ${formatEnvelope(m)} · ${m.maxSpindleSpeed > 0 ? m.maxSpindleSpeed + ' RPM' : ''}`,
    category: 'Máquinas',
    icon: machineIcon(m),
    machine: m,
  }));
}
