/**
 * GLTF manifest — auto-generado por scripts/gen-manifest.py.
 * NO editar a mano — regenerar con el script si agregas/quitas GLBs.
 *
 * Library de masterclass: GLBs CC0 de Kenney (food/city/space/nature/etc).
 * Total entradas se actualiza al regenerar.
 */

export type LibraryCategory =
  | 'food'
  | 'buildings'
  | 'vehicles'
  | 'docs'
  | 'people'
  | 'physics'
  | 'math'
  | 'nature'
  | 'animals'
  | 'lab';

export interface LibraryEntry {
  name: string;
  src: string;
  category: LibraryCategory;
  color: string;
  defaultScale: number;
  source: string;
  available: boolean;
  primaryUse?: string;
}

export const LIBRARY: Record<string, LibraryEntry> = {
  beaver: {
    name: 'beaver',
    src: '/models/library/animals/beaver.glb',
    category: 'animals',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bee: {
    name: 'bee',
    src: '/models/library/animals/bee.glb',
    category: 'animals',
    color: '#FFD86B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bunny: {
    name: 'bunny',
    src: '/models/library/animals/bunny.glb',
    category: 'animals',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cat: {
    name: 'cat',
    src: '/models/library/animals/cat.glb',
    category: 'animals',
    color: '#3A3A3A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  caterpillar: {
    name: 'caterpillar',
    src: '/models/library/animals/caterpillar.glb',
    category: 'animals',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  chick: {
    name: 'chick',
    src: '/models/library/animals/chick.glb',
    category: 'animals',
    color: '#FFD86B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cow: {
    name: 'cow',
    src: '/models/library/animals/cow.glb',
    category: 'animals',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  crab: {
    name: 'crab',
    src: '/models/library/animals/crab.glb',
    category: 'animals',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  deer: {
    name: 'deer',
    src: '/models/library/animals/deer.glb',
    category: 'animals',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  dog: {
    name: 'dog',
    src: '/models/library/animals/dog.glb',
    category: 'animals',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  elephant: {
    name: 'elephant',
    src: '/models/library/animals/elephant.glb',
    category: 'animals',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  fish: {
    name: 'fish',
    src: '/models/library/animals/fish.glb',
    category: 'animals',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  fox: {
    name: 'fox',
    src: '/models/library/animals/fox.glb',
    category: 'animals',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  giraffe: {
    name: 'giraffe',
    src: '/models/library/animals/giraffe.glb',
    category: 'animals',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  hog: {
    name: 'hog',
    src: '/models/library/animals/hog.glb',
    category: 'animals',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  koala: {
    name: 'koala',
    src: '/models/library/animals/koala.glb',
    category: 'animals',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  lion: {
    name: 'lion',
    src: '/models/library/animals/lion.glb',
    category: 'animals',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  monkey: {
    name: 'monkey',
    src: '/models/library/animals/monkey.glb',
    category: 'animals',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  panda: {
    name: 'panda',
    src: '/models/library/animals/panda.glb',
    category: 'animals',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  parrot: {
    name: 'parrot',
    src: '/models/library/animals/parrot.glb',
    category: 'animals',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  penguin: {
    name: 'penguin',
    src: '/models/library/animals/penguin.glb',
    category: 'animals',
    color: '#3A3A3A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  pig: {
    name: 'pig',
    src: '/models/library/animals/pig.glb',
    category: 'animals',
    color: '#FFB6C1',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  polar_bear: {
    name: 'polar_bear',
    src: '/models/library/animals/polar_bear.glb',
    category: 'animals',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tiger: {
    name: 'tiger',
    src: '/models/library/animals/tiger.glb',
    category: 'animals',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_a: {
    name: 'commercial_a',
    src: '/models/library/buildings/commercial_a.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_b: {
    name: 'commercial_b',
    src: '/models/library/buildings/commercial_b.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_d: {
    name: 'commercial_d',
    src: '/models/library/buildings/commercial_d.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_e: {
    name: 'commercial_e',
    src: '/models/library/buildings/commercial_e.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_f: {
    name: 'commercial_f',
    src: '/models/library/buildings/commercial_f.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_g: {
    name: 'commercial_g',
    src: '/models/library/buildings/commercial_g.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  commercial_h: {
    name: 'commercial_h',
    src: '/models/library/buildings/commercial_h.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  factory: {
    name: 'factory',
    src: '/models/library/buildings/factory.glb',
    category: 'buildings',
    color: '#B0B8C0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  gate: {
    name: 'gate',
    src: '/models/library/buildings/gate.glb',
    category: 'buildings',
    color: '#8B7355',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  gate_metal: {
    name: 'gate_metal',
    src: '/models/library/buildings/gate_metal.glb',
    category: 'buildings',
    color: '#8B7355',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house: {
    name: 'house',
    src: '/models/library/buildings/house.glb',
    category: 'buildings',
    color: '#E8B888',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_a: {
    name: 'house_a',
    src: '/models/library/buildings/house_a.glb',
    category: 'buildings',
    color: '#E8B888',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_b: {
    name: 'house_b',
    src: '/models/library/buildings/house_b.glb',
    category: 'buildings',
    color: '#A89B8C',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_c: {
    name: 'house_c',
    src: '/models/library/buildings/house_c.glb',
    category: 'buildings',
    color: '#FFB6C1',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_e: {
    name: 'house_e',
    src: '/models/library/buildings/house_e.glb',
    category: 'buildings',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_i: {
    name: 'house_i',
    src: '/models/library/buildings/house_i.glb',
    category: 'buildings',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_l: {
    name: 'house_l',
    src: '/models/library/buildings/house_l.glb',
    category: 'buildings',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_modular: {
    name: 'house_modular',
    src: '/models/library/buildings/house_modular.glb',
    category: 'buildings',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  house_n: {
    name: 'house_n',
    src: '/models/library/buildings/house_n.glb',
    category: 'buildings',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  office: {
    name: 'office',
    src: '/models/library/buildings/office.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  siege_tower: {
    name: 'siege_tower',
    src: '/models/library/buildings/siege_tower.glb',
    category: 'buildings',
    color: '#C8B89B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  skyscraper_b: {
    name: 'skyscraper_b',
    src: '/models/library/buildings/skyscraper_b.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  skyscraper_d: {
    name: 'skyscraper_d',
    src: '/models/library/buildings/skyscraper_d.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  skyscraper_e: {
    name: 'skyscraper_e',
    src: '/models/library/buildings/skyscraper_e.glb',
    category: 'buildings',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tower: {
    name: 'tower',
    src: '/models/library/buildings/tower.glb',
    category: 'buildings',
    color: '#C8B89B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tower_hex: {
    name: 'tower_hex',
    src: '/models/library/buildings/tower_hex.glb',
    category: 'buildings',
    color: '#C8B89B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tower_square: {
    name: 'tower_square',
    src: '/models/library/buildings/tower_square.glb',
    category: 'buildings',
    color: '#C8B89B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  university: {
    name: 'university',
    src: '/models/library/buildings/university.glb',
    category: 'buildings',
    color: '#C8B498',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  wall: {
    name: 'wall',
    src: '/models/library/buildings/wall.glb',
    category: 'buildings',
    color: '#A89B8C',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  wall_corner: {
    name: 'wall_corner',
    src: '/models/library/buildings/wall_corner.glb',
    category: 'buildings',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  wall_slant: {
    name: 'wall_slant',
    src: '/models/library/buildings/wall_slant.glb',
    category: 'buildings',
    color: '#A89B8C',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  axe: {
    name: 'axe',
    src: '/models/library/docs/axe.glb',
    category: 'docs',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  barrel: {
    name: 'barrel',
    src: '/models/library/docs/barrel.glb',
    category: 'docs',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bottle: {
    name: 'bottle',
    src: '/models/library/docs/bottle.glb',
    category: 'docs',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bottle_large: {
    name: 'bottle_large',
    src: '/models/library/docs/bottle_large.glb',
    category: 'docs',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  briefcase: {
    name: 'briefcase',
    src: '/models/library/docs/briefcase.glb',
    category: 'docs',
    color: '#3A4858',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  candle_grave: {
    name: 'candle_grave',
    src: '/models/library/docs/candle_grave.glb',
    category: 'docs',
    color: '#FFE5A0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cannon: {
    name: 'cannon',
    src: '/models/library/docs/cannon.glb',
    category: 'docs',
    color: '#3A3A3A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cannon_ball: {
    name: 'cannon_ball',
    src: '/models/library/docs/cannon_ball.glb',
    category: 'docs',
    color: '#3A3A3A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cannon_mobile: {
    name: 'cannon_mobile',
    src: '/models/library/docs/cannon_mobile.glb',
    category: 'docs',
    color: '#3A3A3A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  chest: {
    name: 'chest',
    src: '/models/library/docs/chest.glb',
    category: 'docs',
    color: '#C9962B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  chest_dungeon: {
    name: 'chest_dungeon',
    src: '/models/library/docs/chest_dungeon.glb',
    category: 'docs',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  coffin: {
    name: 'coffin',
    src: '/models/library/docs/coffin.glb',
    category: 'docs',
    color: '#5C3A1E',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  computer: {
    name: 'computer',
    src: '/models/library/docs/computer.glb',
    category: 'docs',
    color: '#3A4858',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  crate: {
    name: 'crate',
    src: '/models/library/docs/crate.glb',
    category: 'docs',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  crate_bottles: {
    name: 'crate_bottles',
    src: '/models/library/docs/crate_bottles.glb',
    category: 'docs',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cross: {
    name: 'cross',
    src: '/models/library/docs/cross.glb',
    category: 'docs',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  diploma: {
    name: 'diploma',
    src: '/models/library/docs/diploma.glb',
    category: 'docs',
    color: '#F5E6C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  flag: {
    name: 'flag',
    src: '/models/library/docs/flag.glb',
    category: 'docs',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  flag_castle: {
    name: 'flag_castle',
    src: '/models/library/docs/flag_castle.glb',
    category: 'docs',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  gravestone: {
    name: 'gravestone',
    src: '/models/library/docs/gravestone.glb',
    category: 'docs',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  key: {
    name: 'key',
    src: '/models/library/docs/key.glb',
    category: 'docs',
    color: '#FFD86B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  lantern: {
    name: 'lantern',
    src: '/models/library/docs/lantern.glb',
    category: 'docs',
    color: '#FFE5A0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  mast: {
    name: 'mast',
    src: '/models/library/docs/mast.glb',
    category: 'docs',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  pickaxe: {
    name: 'pickaxe',
    src: '/models/library/docs/pickaxe.glb',
    category: 'docs',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  present: {
    name: 'present',
    src: '/models/library/docs/present.glb',
    category: 'docs',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  present_b: {
    name: 'present_b',
    src: '/models/library/docs/present_b.glb',
    category: 'docs',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  shield_round: {
    name: 'shield_round',
    src: '/models/library/docs/shield_round.glb',
    category: 'docs',
    color: '#C8B89B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  shield_square: {
    name: 'shield_square',
    src: '/models/library/docs/shield_square.glb',
    category: 'docs',
    color: '#A89B8C',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  sword: {
    name: 'sword',
    src: '/models/library/docs/sword.glb',
    category: 'docs',
    color: '#C0C8D0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  apple: {
    name: 'apple',
    src: '/models/library/food/apple.glb',
    category: 'food',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  avocado: {
    name: 'avocado',
    src: '/models/library/food/avocado.glb',
    category: 'food',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  banana: {
    name: 'banana',
    src: '/models/library/food/banana.glb',
    category: 'food',
    color: '#FFE066',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bottle_oil: {
    name: 'bottle_oil',
    src: '/models/library/food/bottle_oil.glb',
    category: 'food',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bread: {
    name: 'bread',
    src: '/models/library/food/bread.glb',
    category: 'food',
    color: '#C9962B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  broccoli: {
    name: 'broccoli',
    src: '/models/library/food/broccoli.glb',
    category: 'food',
    color: '#3D8C5A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  burger: {
    name: 'burger',
    src: '/models/library/food/burger.glb',
    category: 'food',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cake: {
    name: 'cake',
    src: '/models/library/food/cake.glb',
    category: 'food',
    color: '#FFB6C1',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  carrot: {
    name: 'carrot',
    src: '/models/library/food/carrot.glb',
    category: 'food',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cheese: {
    name: 'cheese',
    src: '/models/library/food/cheese.glb',
    category: 'food',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cherry: {
    name: 'cherry',
    src: '/models/library/food/cherry.glb',
    category: 'food',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cocktail: {
    name: 'cocktail',
    src: '/models/library/food/cocktail.glb',
    category: 'food',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  coffee: {
    name: 'coffee',
    src: '/models/library/food/coffee.glb',
    category: 'food',
    color: '#5C3A1E',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cookie: {
    name: 'cookie',
    src: '/models/library/food/cookie.glb',
    category: 'food',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  corn_cob: {
    name: 'corn_cob',
    src: '/models/library/food/corn_cob.glb',
    category: 'food',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  donut: {
    name: 'donut',
    src: '/models/library/food/donut.glb',
    category: 'food',
    color: '#FFB6C1',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  egg: {
    name: 'egg',
    src: '/models/library/food/egg.glb',
    category: 'food',
    color: '#F5E6C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  eggplant: {
    name: 'eggplant',
    src: '/models/library/food/eggplant.glb',
    category: 'food',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  fish_food: {
    name: 'fish_food',
    src: '/models/library/food/fish_food.glb',
    category: 'food',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  lemon: {
    name: 'lemon',
    src: '/models/library/food/lemon.glb',
    category: 'food',
    color: '#FDB813',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  mushroom_food: {
    name: 'mushroom_food',
    src: '/models/library/food/mushroom_food.glb',
    category: 'food',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  orange: {
    name: 'orange',
    src: '/models/library/food/orange.glb',
    category: 'food',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  pineapple: {
    name: 'pineapple',
    src: '/models/library/food/pineapple.glb',
    category: 'food',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  conveyor: {
    name: 'conveyor',
    src: '/models/library/lab/conveyor.glb',
    category: 'lab',
    color: '#A89B8C',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  conveyor_fence: {
    name: 'conveyor_fence',
    src: '/models/library/lab/conveyor_fence.glb',
    category: 'lab',
    color: '#A89B8C',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  crane: {
    name: 'crane',
    src: '/models/library/lab/crane.glb',
    category: 'lab',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  machine: {
    name: 'machine',
    src: '/models/library/lab/machine.glb',
    category: 'lab',
    color: '#B0B8C0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  machine_b: {
    name: 'machine_b',
    src: '/models/library/lab/machine_b.glb',
    category: 'lab',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  pipe_bend: {
    name: 'pipe_bend',
    src: '/models/library/lab/pipe_bend.glb',
    category: 'lab',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  pipe_cross: {
    name: 'pipe_cross',
    src: '/models/library/lab/pipe_cross.glb',
    category: 'lab',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  coin_bronze: {
    name: 'coin_bronze',
    src: '/models/library/math/coin_bronze.glb',
    category: 'math',
    color: '#CD7F32',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  coin_gold: {
    name: 'coin_gold',
    src: '/models/library/math/coin_gold.glb',
    category: 'math',
    color: '#FFD86B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  coin_silver: {
    name: 'coin_silver',
    src: '/models/library/math/coin_silver.glb',
    category: 'math',
    color: '#C0C8D0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  decision_tree: {
    name: 'decision_tree',
    src: '/models/library/math/decision_tree.glb',
    category: 'math',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  funnel: {
    name: 'funnel',
    src: '/models/library/math/funnel.glb',
    category: 'math',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  funnel_long: {
    name: 'funnel_long',
    src: '/models/library/math/funnel_long.glb',
    category: 'math',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  helix: {
    name: 'helix',
    src: '/models/library/math/helix.glb',
    category: 'math',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  helix_large: {
    name: 'helix_large',
    src: '/models/library/math/helix_large.glb',
    category: 'math',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  marble: {
    name: 'marble',
    src: '/models/library/math/marble.glb',
    category: 'math',
    color: '#FDB813',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  marble_low: {
    name: 'marble_low',
    src: '/models/library/math/marble_low.glb',
    category: 'math',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  split: {
    name: 'split',
    src: '/models/library/math/split.glb',
    category: 'math',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  star: {
    name: 'star',
    src: '/models/library/math/star.glb',
    category: 'math',
    color: '#FFD86B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bamboo: {
    name: 'bamboo',
    src: '/models/library/nature/bamboo.glb',
    category: 'nature',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bush: {
    name: 'bush',
    src: '/models/library/nature/bush.glb',
    category: 'nature',
    color: '#3D8C5A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  bush_large: {
    name: 'bush_large',
    src: '/models/library/nature/bush_large.glb',
    category: 'nature',
    color: '#3D8C5A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cactus: {
    name: 'cactus',
    src: '/models/library/nature/cactus.glb',
    category: 'nature',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cactus_short: {
    name: 'cactus_short',
    src: '/models/library/nature/cactus_short.glb',
    category: 'nature',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  campfire: {
    name: 'campfire',
    src: '/models/library/nature/campfire.glb',
    category: 'nature',
    color: '#FF6B35',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  campfire_logs: {
    name: 'campfire_logs',
    src: '/models/library/nature/campfire_logs.glb',
    category: 'nature',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  candle: {
    name: 'candle',
    src: '/models/library/nature/candle.glb',
    category: 'nature',
    color: '#FFE5A0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  corn: {
    name: 'corn',
    src: '/models/library/nature/corn.glb',
    category: 'nature',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  fence: {
    name: 'fence',
    src: '/models/library/nature/fence.glb',
    category: 'nature',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  flower: {
    name: 'flower',
    src: '/models/library/nature/flower.glb',
    category: 'nature',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  flower_purple: {
    name: 'flower_purple',
    src: '/models/library/nature/flower_purple.glb',
    category: 'nature',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  flower_yellow: {
    name: 'flower_yellow',
    src: '/models/library/nature/flower_yellow.glb',
    category: 'nature',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  log: {
    name: 'log',
    src: '/models/library/nature/log.glb',
    category: 'nature',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  log_stack: {
    name: 'log_stack',
    src: '/models/library/nature/log_stack.glb',
    category: 'nature',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  mushroom: {
    name: 'mushroom',
    src: '/models/library/nature/mushroom.glb',
    category: 'nature',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  mushroom_tan: {
    name: 'mushroom_tan',
    src: '/models/library/nature/mushroom_tan.glb',
    category: 'nature',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  rock: {
    name: 'rock',
    src: '/models/library/nature/rock.glb',
    category: 'nature',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tent: {
    name: 'tent',
    src: '/models/library/nature/tent.glb',
    category: 'nature',
    color: '#8B5A2B',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree: {
    name: 'tree',
    src: '/models/library/nature/tree.glb',
    category: 'nature',
    color: '#2D8659',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_blocks: {
    name: 'tree_blocks',
    src: '/models/library/nature/tree_blocks.glb',
    category: 'nature',
    color: '#3D8C5A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_decorated: {
    name: 'tree_decorated',
    src: '/models/library/nature/tree_decorated.glb',
    category: 'nature',
    color: '#2D8659',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_default: {
    name: 'tree_default',
    src: '/models/library/nature/tree_default.glb',
    category: 'nature',
    color: '#3D8C5A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_fall: {
    name: 'tree_fall',
    src: '/models/library/nature/tree_fall.glb',
    category: 'nature',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_log: {
    name: 'tree_log',
    src: '/models/library/nature/tree_log.glb',
    category: 'nature',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_oak: {
    name: 'tree_oak',
    src: '/models/library/nature/tree_oak.glb',
    category: 'nature',
    color: '#3D8C5A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_palm: {
    name: 'tree_palm',
    src: '/models/library/nature/tree_palm.glb',
    category: 'nature',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_pine: {
    name: 'tree_pine',
    src: '/models/library/nature/tree_pine.glb',
    category: 'nature',
    color: '#2D8659',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tree_snow: {
    name: 'tree_snow',
    src: '/models/library/nature/tree_snow.glb',
    category: 'nature',
    color: '#E8E8F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  wood: {
    name: 'wood',
    src: '/models/library/nature/wood.glb',
    category: 'nature',
    color: '#A0522D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  alien: {
    name: 'alien',
    src: '/models/library/people/alien.glb',
    category: 'people',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  astronaut: {
    name: 'astronaut',
    src: '/models/library/people/astronaut.glb',
    category: 'people',
    color: '#E8E8F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  astronaut_b: {
    name: 'astronaut_b',
    src: '/models/library/people/astronaut_b.glb',
    category: 'people',
    color: '#E8E8F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_a: {
    name: 'civilian_a',
    src: '/models/library/people/civilian_a.glb',
    category: 'people',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_b: {
    name: 'civilian_b',
    src: '/models/library/people/civilian_b.glb',
    category: 'people',
    color: '#3B82F6',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_c: {
    name: 'civilian_c',
    src: '/models/library/people/civilian_c.glb',
    category: 'people',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_d: {
    name: 'civilian_d',
    src: '/models/library/people/civilian_d.glb',
    category: 'people',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_e: {
    name: 'civilian_e',
    src: '/models/library/people/civilian_e.glb',
    category: 'people',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_f: {
    name: 'civilian_f',
    src: '/models/library/people/civilian_f.glb',
    category: 'people',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_g: {
    name: 'civilian_g',
    src: '/models/library/people/civilian_g.glb',
    category: 'people',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_h: {
    name: 'civilian_h',
    src: '/models/library/people/civilian_h.glb',
    category: 'people',
    color: '#3B82F6',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_i: {
    name: 'civilian_i',
    src: '/models/library/people/civilian_i.glb',
    category: 'people',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_j: {
    name: 'civilian_j',
    src: '/models/library/people/civilian_j.glb',
    category: 'people',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_k: {
    name: 'civilian_k',
    src: '/models/library/people/civilian_k.glb',
    category: 'people',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  civilian_l: {
    name: 'civilian_l',
    src: '/models/library/people/civilian_l.glb',
    category: 'people',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  ghost: {
    name: 'ghost',
    src: '/models/library/people/ghost.glb',
    category: 'people',
    color: '#C8C8E0',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  skeleton: {
    name: 'skeleton',
    src: '/models/library/people/skeleton.glb',
    category: 'people',
    color: '#E8E8E8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  snowman: {
    name: 'snowman',
    src: '/models/library/people/snowman.glb',
    category: 'people',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  soldier: {
    name: 'soldier',
    src: '/models/library/people/soldier.glb',
    category: 'people',
    color: '#3A4858',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  cargo_ship: {
    name: 'cargo_ship',
    src: '/models/library/physics/cargo_ship.glb',
    category: 'physics',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  crystals: {
    name: 'crystals',
    src: '/models/library/physics/crystals.glb',
    category: 'physics',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  crystals_large: {
    name: 'crystals_large',
    src: '/models/library/physics/crystals_large.glb',
    category: 'physics',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  meteor: {
    name: 'meteor',
    src: '/models/library/physics/meteor.glb',
    category: 'physics',
    color: '#B8856A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  meteor_b: {
    name: 'meteor_b',
    src: '/models/library/physics/meteor_b.glb',
    category: 'physics',
    color: '#9CA3AF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  miner_ship: {
    name: 'miner_ship',
    src: '/models/library/physics/miner_ship.glb',
    category: 'physics',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  rocket_base: {
    name: 'rocket_base',
    src: '/models/library/physics/rocket_base.glb',
    category: 'physics',
    color: '#A8B5C8',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  rocket_fins: {
    name: 'rocket_fins',
    src: '/models/library/physics/rocket_fins.glb',
    category: 'physics',
    color: '#3A4858',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  rocket_top: {
    name: 'rocket_top',
    src: '/models/library/physics/rocket_top.glb',
    category: 'physics',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  rover: {
    name: 'rover',
    src: '/models/library/physics/rover.glb',
    category: 'physics',
    color: '#FFB870',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  satellite: {
    name: 'satellite',
    src: '/models/library/physics/satellite.glb',
    category: 'physics',
    color: '#E8E8F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  satellite_large: {
    name: 'satellite_large',
    src: '/models/library/physics/satellite_large.glb',
    category: 'physics',
    color: '#E8E8F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  spacecraft: {
    name: 'spacecraft',
    src: '/models/library/physics/spacecraft.glb',
    category: 'physics',
    color: '#7FB0FF',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  spacecraft_a: {
    name: 'spacecraft_a',
    src: '/models/library/physics/spacecraft_a.glb',
    category: 'physics',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  spacecraft_b: {
    name: 'spacecraft_b',
    src: '/models/library/physics/spacecraft_b.glb',
    category: 'physics',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  ambulance: {
    name: 'ambulance',
    src: '/models/library/vehicles/ambulance.glb',
    category: 'vehicles',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  delivery: {
    name: 'delivery',
    src: '/models/library/vehicles/delivery.glb',
    category: 'vehicles',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  firetruck: {
    name: 'firetruck',
    src: '/models/library/vehicles/firetruck.glb',
    category: 'vehicles',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  garbage_truck: {
    name: 'garbage_truck',
    src: '/models/library/vehicles/garbage_truck.glb',
    category: 'vehicles',
    color: '#5BA34A',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  kart: {
    name: 'kart',
    src: '/models/library/vehicles/kart.glb',
    category: 'vehicles',
    color: '#FF7A45',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  pickup: {
    name: 'pickup',
    src: '/models/library/vehicles/pickup.glb',
    category: 'vehicles',
    color: '#FBBF24',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  police: {
    name: 'police',
    src: '/models/library/vehicles/police.glb',
    category: 'vehicles',
    color: '#3A4858',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  race_future: {
    name: 'race_future',
    src: '/models/library/vehicles/race_future.glb',
    category: 'vehicles',
    color: '#A78BFA',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  race_green: {
    name: 'race_green',
    src: '/models/library/vehicles/race_green.glb',
    category: 'vehicles',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  race_red: {
    name: 'race_red',
    src: '/models/library/vehicles/race_red.glb',
    category: 'vehicles',
    color: '#D7263D',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  race_white: {
    name: 'race_white',
    src: '/models/library/vehicles/race_white.glb',
    category: 'vehicles',
    color: '#F5F5F5',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  sedan: {
    name: 'sedan',
    src: '/models/library/vehicles/sedan.glb',
    category: 'vehicles',
    color: '#34D399',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
  tractor: {
    name: 'tractor',
    src: '/models/library/vehicles/tractor.glb',
    category: 'vehicles',
    color: '#3A4858',
    defaultScale: 1.0,
    source: 'Kenney CC0',
    available: true,
  },
};

export const LIBRARY_LIST: LibraryEntry[] = Object.values(LIBRARY);

export function entriesByCategory(category: LibraryCategory): LibraryEntry[] {
  return LIBRARY_LIST.filter(e => e.category === category);
}

export const CATEGORIES: LibraryCategory[] = ['food', 'buildings', 'docs', 'vehicles', 'people', 'physics', 'math', 'nature', 'animals', 'lab'];