/**
 * Catálogo del Premio Nobel de Física (1901-2024).
 *
 * 118 premios entregados desde 1901 a más de 220 personas. Cada entrada es
 * UNA lección potencial del módulo de física. Lo mismo que hicimos con
 * Economía pero a mayor escala — la física es la disciplina más antigua
 * del Nobel y la que ha movido más fronteras en el siglo XX.
 *
 * Los bloques NO son cronológicos: están agrupados por TEMA pedagógico
 * para que un alumno pueda seguir el hilo conceptual. Dentro de cada
 * bloque, el orden es cronológico para mostrar la evolución de la idea.
 *
 * `status: 'live'` significa que la masterclass ya está producida y enlaza
 * a `/masterclass.html?id=<classId>`. `status: 'pending'` aparece como card
 * en gris en el portal, próxima a producir.
 */

export type NobelStatus = 'live' | 'pending';

export interface PhysicsLaureate {
  /** Slug del premio. Usado como id de masterclass cuando esté live. */
  id: string;
  /** Año del premio. */
  year: number;
  /** Lista de premiados (1-3 personas). */
  laureates: string[];
  /** Bloque temático. Determina el color y el orden visual. */
  block: PhysicsBlock;
  /** Título corto de la lección — el "hook". */
  title: string;
  /** Subtítulo: qué premió oficialmente el comité (en español). */
  subtitle: string;
  /** Frase de impacto: qué cambia entender esto. */
  impact: string;
  /** Estado de producción. */
  status: NobelStatus;
  /** Si status === 'live', el classId del masterclass. */
  classId?: string;
}

export type PhysicsBlock =
  | 'cuantica-fundamentos'
  | 'relatividad-gravedad'
  | 'particulas-elementales'
  | 'nucleo'
  | 'cosmologia-astrofisica'
  | 'superconductividad-superfluidos'
  | 'materia-condensada'
  | 'semiconductores-electronica'
  | 'optica-laseres'
  | 'tecnicas-experimentales'
  | 'info-cuantica'
  | 'complejidad-clima-ml';

export interface PhysicsBlockMeta {
  id: PhysicsBlock;
  name: string;
  description: string;
  color: string;
  colorBg: string;
  colorEmissive: string;
  order: number;
}

export const PHYSICS_BLOCKS: PhysicsBlockMeta[] = [
  {
    id: 'cuantica-fundamentos',
    name: 'Cuántica · fundamentos',
    description: 'Los cimientos. Planck, Einstein, Bohr, Heisenberg, Schrödinger, Dirac. La mecánica que rompió el sentido común.',
    color: '#A78BFA',
    colorBg: '#1E1338',
    colorEmissive: '#6D28D9',
    order: 1,
  },
  {
    id: 'relatividad-gravedad',
    name: 'Relatividad y gravedad',
    description: 'El espacio-tiempo curvo. Ondas gravitacionales. Agujeros negros. Lo más grande de lo grande.',
    color: '#FDB813',
    colorBg: '#2A1A03',
    colorEmissive: '#B45309',
    order: 2,
  },
  {
    id: 'particulas-elementales',
    name: 'Partículas elementales',
    description: 'El zoológico subatómico. Electrón, quark, neutrino, Higgs. El Modelo Estándar paso a paso.',
    color: '#F472B6',
    colorBg: '#2A0E22',
    colorEmissive: '#BE185D',
    order: 3,
  },
  {
    id: 'nucleo',
    name: 'Núcleo atómico',
    description: 'Radiactividad, fisión, fusión. Lo que está dentro del átomo y por qué brilla.',
    color: '#EF4444',
    colorBg: '#2A0B0B',
    colorEmissive: '#991B1B',
    order: 4,
  },
  {
    id: 'cosmologia-astrofisica',
    name: 'Cosmología y astrofísica',
    description: 'El Big Bang, el fondo cósmico, las supernovas, los exoplanetas. El universo a su mayor escala.',
    color: '#60A5FA',
    colorBg: '#0B2138',
    colorEmissive: '#1E40AF',
    order: 5,
  },
  {
    id: 'superconductividad-superfluidos',
    name: 'Superconductividad y superfluidos',
    description: 'Resistencia cero. Viscosidad cero. La materia cuántica a escala macroscópica.',
    color: '#22D3EE',
    colorBg: '#082831',
    colorEmissive: '#0E7490',
    order: 6,
  },
  {
    id: 'materia-condensada',
    name: 'Materia condensada',
    description: 'Cristales, magnetismo, transiciones de fase, topología. La física de los sólidos reales.',
    color: '#34D399',
    colorBg: '#062E20',
    colorEmissive: '#047857',
    order: 7,
  },
  {
    id: 'semiconductores-electronica',
    name: 'Semiconductores y electrónica',
    description: 'El transistor, el chip, el LED, la fibra óptica. La física que construyó tu celular.',
    color: '#FB923C',
    colorBg: '#2A1407',
    colorEmissive: '#C2410C',
    order: 8,
  },
  {
    id: 'optica-laseres',
    name: 'Óptica y láseres',
    description: 'De la difracción a los pulsos de attosegundo. Cómo controlamos la luz para ver lo invisible.',
    color: '#FACC15',
    colorBg: '#2A2003',
    colorEmissive: '#A16207',
    order: 9,
  },
  {
    id: 'tecnicas-experimentales',
    name: 'Técnicas experimentales',
    description: 'Rayos X, microscopios, aceleradores, cámaras de niebla. Las herramientas que destaparon todo lo demás.',
    color: '#94A3B8',
    colorBg: '#1A2030',
    colorEmissive: '#475569',
    order: 10,
  },
  {
    id: 'info-cuantica',
    name: 'Información cuántica',
    description: 'Entrelazamiento, teleportación, cómputo cuántico. La nueva era — Bell, Aspect, Wineland, Haroche.',
    color: '#D946EF',
    colorBg: '#2A0F30',
    colorEmissive: '#A21CAF',
    order: 11,
  },
  {
    id: 'complejidad-clima-ml',
    name: 'Complejidad, clima y aprendizaje',
    description: 'Sistemas desordenados, modelos climáticos, redes neuronales. Cuando la física sale de su disciplina y resuelve TODO.',
    color: '#E2E8F0',
    colorBg: '#1A1F2A',
    colorEmissive: '#64748B',
    order: 12,
  },
];

/**
 * Los premios desde 1901. Datos verificados contra NobelPrize.org.
 * Las frases de "impact" son redacción nuestra, pensadas para el
 * alumno latinoamericano.
 */
export const PHYSICS_CATALOG: PhysicsLaureate[] = [
  // ═══════════════════════ CUÁNTICA · FUNDAMENTOS ═══════════════════════
  {
    id: 'phys-1918-planck',
    year: 1918,
    laureates: ['Max Planck'],
    block: 'cuantica-fundamentos',
    title: 'El cuanto: el día que la energía dejó de ser continua',
    subtitle: 'Por el descubrimiento de los cuantos de energía.',
    impact: 'Para explicar por qué un horno no emite radiación infinita, inventó algo que no se creía ni él. Nació la mecánica cuántica.',
    status: 'pending',
  },
  {
    id: 'phys-1921-einstein',
    year: 1921,
    laureates: ['Albert Einstein'],
    block: 'cuantica-fundamentos',
    title: 'El efecto fotoeléctrico (no la relatividad)',
    subtitle: 'Por sus servicios a la física teórica, y especialmente por su descubrimiento de la ley del efecto fotoeléctrico.',
    impact: 'El comité tuvo miedo de premiarle la relatividad. Le dieron el Nobel por demostrar que la luz son fotones — la base del láser y el panel solar.',
    status: 'live',
    classId: 'phys-einstein-pe',
  },
  {
    id: 'phys-1922-bohr',
    year: 1922,
    laureates: ['Niels Bohr'],
    block: 'cuantica-fundamentos',
    title: 'El átomo de Bohr: por qué los electrones no caen al núcleo',
    subtitle: 'Por sus investigaciones sobre la estructura de los átomos y la radiación que emiten.',
    impact: 'Inventó las órbitas cuantizadas. Cada raya del espectro del hidrógeno es un salto entre niveles. La química moderna empezó aquí.',
    status: 'pending',
  },
  {
    id: 'phys-1925-franck-hertz',
    year: 1925,
    laureates: ['James Franck', 'Gustav Hertz'],
    block: 'cuantica-fundamentos',
    title: 'Franck-Hertz: la prueba experimental de Bohr',
    subtitle: 'Por el descubrimiento de las leyes que rigen el impacto de un electrón sobre un átomo.',
    impact: 'Dispararon electrones contra vapor de mercurio y midieron escalones — la confirmación de que los niveles de energía existen.',
    status: 'pending',
  },
  {
    id: 'phys-1929-debroglie',
    year: 1929,
    laureates: ['Louis de Broglie'],
    block: 'cuantica-fundamentos',
    title: 'La naturaleza ondulatoria de la materia',
    subtitle: 'Por su descubrimiento de la naturaleza ondulatoria de los electrones.',
    impact: 'Si la luz es partícula y onda, ¿por qué no el electrón? Su tesis doctoral cambió la mecánica entera. Su director: Einstein la respaldó.',
    status: 'pending',
  },
  {
    id: 'phys-1932-heisenberg',
    year: 1932,
    laureates: ['Werner Heisenberg'],
    block: 'cuantica-fundamentos',
    title: 'El principio de incertidumbre',
    subtitle: 'Por la creación de la mecánica cuántica.',
    impact: 'No puedes saber posición y momento a la vez. No es un límite tecnológico — es la naturaleza misma. Mecánica matricial.',
    status: 'pending',
  },
  {
    id: 'phys-1933-schrodinger-dirac',
    year: 1933,
    laureates: ['Erwin Schrödinger', 'Paul Dirac'],
    block: 'cuantica-fundamentos',
    title: 'La ecuación de onda y la ecuación de Dirac',
    subtitle: 'Por el descubrimiento de nuevas formas productivas de teoría atómica.',
    impact: 'Schrödinger: la función de onda. Dirac: la unió con la relatividad y predijo la antimateria. Las dos ecuaciones más bellas del siglo XX.',
    status: 'pending',
  },
  {
    id: 'phys-1945-pauli',
    year: 1945,
    laureates: ['Wolfgang Pauli'],
    block: 'cuantica-fundamentos',
    title: 'El principio de exclusión',
    subtitle: 'Por el descubrimiento del principio de exclusión, también llamado principio de Pauli.',
    impact: 'Por qué dos electrones no pueden ocupar el mismo estado. Por qué existe la tabla periódica. Por qué la materia es sólida.',
    status: 'pending',
  },
  {
    id: 'phys-1954-born-bothe',
    year: 1954,
    laureates: ['Max Born', 'Walther Bothe'],
    block: 'cuantica-fundamentos',
    title: 'La interpretación probabilística',
    subtitle: 'Born: por la interpretación estadística de la función de onda. Bothe: por el método de coincidencia.',
    impact: 'Born dijo: |ψ|² es una probabilidad. Einstein no le habló más. La cuántica dejó de ser determinista — para siempre.',
    status: 'pending',
  },
  {
    id: 'phys-1955-lamb-kusch',
    year: 1955,
    laureates: ['Willis Lamb', 'Polykarp Kusch'],
    block: 'cuantica-fundamentos',
    title: 'El corrimiento de Lamb',
    subtitle: 'Lamb: por descubrimientos sobre la estructura fina del hidrógeno. Kusch: por la medición precisa del momento magnético del electrón.',
    impact: 'Midieron una pequeña discrepancia con Dirac — y fue el detonante de la electrodinámica cuántica (QED).',
    status: 'pending',
  },
  {
    id: 'phys-1963-wigner-mayer-jensen',
    year: 1963,
    laureates: ['Eugene Wigner', 'Maria Goeppert Mayer', 'J. Hans D. Jensen'],
    block: 'cuantica-fundamentos',
    title: 'Simetrías y el modelo de capas nuclear',
    subtitle: 'Wigner: por la teoría del núcleo y partículas elementales, en especial las simetrías. Mayer y Jensen: por descubrimientos sobre la estructura nuclear de capas.',
    impact: 'Wigner: la simetría es lo más profundo de la física. Goeppert Mayer: segunda mujer Nobel de Física después de Marie Curie (¡60 años después!).',
    status: 'pending',
  },
  {
    id: 'phys-1965-qed',
    year: 1965,
    laureates: ['Sin-Itiro Tomonaga', 'Julian Schwinger', 'Richard Feynman'],
    block: 'cuantica-fundamentos',
    title: 'QED — la teoría más precisa de la historia',
    subtitle: 'Por su trabajo fundamental en electrodinámica cuántica, con consecuencias profundas para la física de partículas elementales.',
    impact: 'Predicciones coincidentes con experimento a 12 decimales. Feynman regaló los diagramas. La QED es el modelo de cómo se hace física moderna.',
    status: 'pending',
  },
  {
    id: 'phys-1989-ramsey-dehmelt-paul',
    year: 1989,
    laureates: ['Norman Ramsey', 'Hans Dehmelt', 'Wolfgang Paul'],
    block: 'cuantica-fundamentos',
    title: 'Atrapando un solo átomo',
    subtitle: 'Ramsey: método de campos oscilatorios separados (relojes atómicos). Dehmelt y Paul: técnicas de trampas iónicas.',
    impact: 'Antes de ellos, "medir un átomo" era una idealización. Ellos lo aislaron uno por uno. Hoy: base de los relojes atómicos y el cómputo cuántico iónico.',
    status: 'pending',
  },

  // ═══════════════════════ RELATIVIDAD Y GRAVEDAD ═══════════════════════
  {
    id: 'phys-1993-hulse-taylor',
    year: 1993,
    laureates: ['Russell Hulse', 'Joseph Taylor'],
    block: 'relatividad-gravedad',
    title: 'El pulsar binario: la primera evidencia de ondas gravitacionales',
    subtitle: 'Por el descubrimiento de un nuevo tipo de púlsar que abrió posibilidades para el estudio de la gravitación.',
    impact: 'Encontraron dos estrellas de neutrones orbitando. La órbita se reducía exactamente como predecía Einstein — radiando ondas gravitacionales.',
    status: 'pending',
  },
  {
    id: 'phys-2017-ligo',
    year: 2017,
    laureates: ['Rainer Weiss', 'Barry Barish', 'Kip Thorne'],
    block: 'relatividad-gravedad',
    title: 'LIGO: escuchando dos agujeros negros chocar',
    subtitle: 'Por contribuciones decisivas al detector LIGO y la observación de ondas gravitacionales.',
    impact: 'El 14 de septiembre de 2015 detectamos por primera vez una onda gravitacional. Era la fusión de dos agujeros negros a 1.300 millones de años luz.',
    status: 'pending',
  },
  {
    id: 'phys-2020-blackhole',
    year: 2020,
    laureates: ['Roger Penrose', 'Reinhard Genzel', 'Andrea Ghez'],
    block: 'relatividad-gravedad',
    title: 'Agujeros negros: del teorema a la observación',
    subtitle: 'Penrose: por demostrar que la formación de agujeros negros es una predicción robusta de la relatividad general. Genzel y Ghez: por el descubrimiento del objeto compacto supermasivo en el centro de nuestra galaxia.',
    impact: 'Penrose demostró que los agujeros negros NO son una curiosidad matemática — son inevitables. Genzel y Ghez nos mostraron uno en el centro de la Vía Láctea.',
    status: 'live',
    classId: 'blackhole',
  },
  {
    id: 'phys-2023-attosecond',
    year: 2023,
    laureates: ['Pierre Agostini', 'Ferenc Krausz', 'Anne L’Huillier'],
    block: 'optica-laseres',
    title: 'Pulsos de attosegundo: viendo electrones en movimiento',
    subtitle: 'Por métodos experimentales que generan pulsos de luz de attosegundo para el estudio de la dinámica electrónica en la materia.',
    impact: 'Un attosegundo es 10⁻¹⁸ segundos — un electrón tarda eso en cruzar un átomo. Por primera vez podemos filmarlos.',
    status: 'pending',
  },

  // ═══════════════════════ PARTÍCULAS ELEMENTALES ═══════════════════════
  {
    id: 'phys-1936-hess-anderson',
    year: 1936,
    laureates: ['Victor Hess', 'Carl Anderson'],
    block: 'particulas-elementales',
    title: 'Rayos cósmicos y el positrón',
    subtitle: 'Hess: por el descubrimiento de la radiación cósmica. Anderson: por el descubrimiento del positrón.',
    impact: 'Anderson encontró la antimateria que Dirac había predicho. Hess descubrió que el espacio nos bombardea con partículas — los rayos cósmicos.',
    status: 'pending',
  },
  {
    id: 'phys-1949-yukawa',
    year: 1949,
    laureates: ['Hideki Yukawa'],
    block: 'particulas-elementales',
    title: 'La predicción del mesón',
    subtitle: 'Por su predicción de la existencia de mesones con base en trabajos teóricos sobre fuerzas nucleares.',
    impact: 'Predijo que una partícula intermedia mantenía unido el núcleo. Lo llamaron pion. Primer Nobel japonés y un milagro de la teoría pura.',
    status: 'pending',
  },
  {
    id: 'phys-1950-powell',
    year: 1950,
    laureates: ['Cecil Powell'],
    block: 'particulas-elementales',
    title: 'El pion en una placa fotográfica',
    subtitle: 'Por su desarrollo del método fotográfico de estudio de procesos nucleares y los descubrimientos relativos a los mesones.',
    impact: 'Detectó al pion de Yukawa con placas fotográficas expuestas en montañas. Antes de los aceleradores, los rayos cósmicos eran el laboratorio.',
    status: 'pending',
  },
  {
    id: 'phys-1957-yang-lee',
    year: 1957,
    laureates: ['Chen-Ning Yang', 'Tsung-Dao Lee'],
    block: 'particulas-elementales',
    title: 'Paridad: el espejo que se rompió',
    subtitle: 'Por su investigación penetrante en las llamadas leyes de paridad, que llevó a descubrimientos importantes sobre las partículas elementales.',
    impact: 'Demostraron que la naturaleza distingue entre izquierda y derecha — algo que se creía imposible. El experimento de Wu lo confirmó.',
    status: 'pending',
  },
  {
    id: 'phys-1959-segre-chamberlain',
    year: 1959,
    laureates: ['Emilio Segrè', 'Owen Chamberlain'],
    block: 'particulas-elementales',
    title: 'El antiprotón',
    subtitle: 'Por su descubrimiento del antiprotón.',
    impact: 'Construyeron un acelerador específicamente para encontrar la antimateria pesada. Lo lograron en Berkeley en 1955.',
    status: 'pending',
  },
  {
    id: 'phys-1969-gellmann',
    year: 1969,
    laureates: ['Murray Gell-Mann'],
    block: 'particulas-elementales',
    title: 'Quarks: la clasificación del zoo',
    subtitle: 'Por sus contribuciones y descubrimientos sobre la clasificación de partículas elementales y sus interacciones.',
    impact: 'En los 60s había docenas de partículas "elementales" — un caos. Gell-Mann las ordenó con un patrón octaédrico. Predijo quarks años antes de detectarlos.',
    status: 'pending',
  },
  {
    id: 'phys-1976-richter-ting',
    year: 1976,
    laureates: ['Burton Richter', 'Samuel Ting'],
    block: 'particulas-elementales',
    title: 'El quark charm — la J/ψ',
    subtitle: 'Por su trabajo pionero en el descubrimiento de un tipo pesado de partícula elemental.',
    impact: 'Dos equipos independientes la encontraron a la vez. Confirmó la existencia del quark "encanto" y unificó el Modelo Estándar.',
    status: 'pending',
  },
  {
    id: 'phys-1979-electroweak',
    year: 1979,
    laureates: ['Sheldon Glashow', 'Abdus Salam', 'Steven Weinberg'],
    block: 'particulas-elementales',
    title: 'La unificación electrodébil',
    subtitle: 'Por contribuciones a la teoría unificada de las interacciones débil y electromagnética entre partículas elementales.',
    impact: 'Demostraron que el electromagnetismo y la fuerza débil son la MISMA fuerza a alta energía. El primer paso a una teoría del todo.',
    status: 'pending',
  },
  {
    id: 'phys-1980-cronin-fitch',
    year: 1980,
    laureates: ['James Cronin', 'Val Fitch'],
    block: 'particulas-elementales',
    title: 'Violación de CP: por qué existe la materia',
    subtitle: 'Por el descubrimiento de violaciones de los principios fundamentales de simetría en el decaimiento de mesones K neutros.',
    impact: 'Encontraron una asimetría diminuta entre materia y antimateria — la única razón por la cual el universo no se autoaniquiló después del Big Bang.',
    status: 'pending',
  },
  {
    id: 'phys-1984-rubbia-vdmeer',
    year: 1984,
    laureates: ['Carlo Rubbia', 'Simon van der Meer'],
    block: 'particulas-elementales',
    title: 'Los bosones W y Z',
    subtitle: 'Por contribuciones decisivas al descubrimiento de las partículas W y Z, comunicadoras de la interacción débil.',
    impact: 'Confirmaron experimentalmente la unificación electrodébil. Van der Meer inventó el "stochastic cooling" — geniales hacks que hicieron posible el CERN.',
    status: 'pending',
  },
  {
    id: 'phys-1988-lederman-schwartz-steinberger',
    year: 1988,
    laureates: ['Leon Lederman', 'Melvin Schwartz', 'Jack Steinberger'],
    block: 'particulas-elementales',
    title: 'El neutrino del muón',
    subtitle: 'Por el método del haz de neutrinos y la demostración de la estructura doblete de los leptones mediante el descubrimiento del neutrino del muón.',
    impact: 'Hay tres tipos de neutrinos, no uno. Confirmó la estructura de "familias" de partículas.',
    status: 'pending',
  },
  {
    id: 'phys-1990-deep-inelastic',
    year: 1990,
    laureates: ['Jerome Friedman', 'Henry Kendall', 'Richard Taylor'],
    block: 'particulas-elementales',
    title: 'Dispersión inelástica profunda: los quarks son reales',
    subtitle: 'Por sus investigaciones pioneras sobre la dispersión profundamente inelástica de electrones contra protones y neutrones, cruciales para el modelo de quarks.',
    impact: 'Dispararon electrones a protones y vieron que rebotaban como si chocaran con bolitas duras dentro. Los quarks dejaron de ser teoría.',
    status: 'pending',
  },
  {
    id: 'phys-1995-perl-reines',
    year: 1995,
    laureates: ['Martin Perl', 'Frederick Reines'],
    block: 'particulas-elementales',
    title: 'El leptón tau y la detección del neutrino',
    subtitle: 'Perl: por el descubrimiento del leptón tau. Reines: por la detección del neutrino.',
    impact: 'Reines tardó 20 años en cazar la partícula más fantasmal del universo. Perl encontró el tercer leptón — más pesado que el electrón pero igual de elemental.',
    status: 'pending',
  },
  {
    id: 'phys-1999-thooft-veltman',
    year: 1999,
    laureates: ['Gerardus ‘t Hooft', 'Martinus Veltman'],
    block: 'particulas-elementales',
    title: 'Renormalización: domando el infinito',
    subtitle: 'Por dilucidar la estructura cuántica de las interacciones electrodébiles en física.',
    impact: 'Demostraron que la teoría electrodébil daba predicciones finitas. Sin su trabajo, el Modelo Estándar no se podría calcular.',
    status: 'pending',
  },
  {
    id: 'phys-2004-qcd',
    year: 2004,
    laureates: ['David Gross', 'H. David Politzer', 'Frank Wilczek'],
    block: 'particulas-elementales',
    title: 'Libertad asintótica en QCD',
    subtitle: 'Por el descubrimiento de la libertad asintótica en la teoría de la interacción fuerte.',
    impact: 'Los quarks están más sueltos cuanto más cerca están entre sí — al revés que cualquier otra fuerza. Por eso es imposible aislar un quark.',
    status: 'pending',
  },
  {
    id: 'phys-2008-nambu-kobayashi-maskawa',
    year: 2008,
    laureates: ['Yoichiro Nambu', 'Makoto Kobayashi', 'Toshihide Maskawa'],
    block: 'particulas-elementales',
    title: 'Ruptura espontánea de simetría',
    subtitle: 'Nambu: por el descubrimiento del mecanismo de ruptura espontánea de simetría en física subatómica. Kobayashi y Maskawa: por el origen de la violación CP.',
    impact: 'Nambu: las leyes son simétricas pero el mundo no — porque la simetría se rompe sola. Idea seminal del mecanismo de Higgs.',
    status: 'pending',
  },
  {
    id: 'phys-2013-higgs',
    year: 2013,
    laureates: ['François Englert', 'Peter Higgs'],
    block: 'particulas-elementales',
    title: 'El bosón de Higgs',
    subtitle: 'Por el descubrimiento teórico de un mecanismo que contribuye a nuestra comprensión del origen de la masa de las partículas subatómicas.',
    impact: 'Predijeron en 1964 una partícula que daría masa a todo lo demás. La encontraron en el LHC en 2012. Cerró el Modelo Estándar.',
    status: 'pending',
  },
  {
    id: 'phys-2015-neutrino-oscillations',
    year: 2015,
    laureates: ['Takaaki Kajita', 'Arthur McDonald'],
    block: 'particulas-elementales',
    title: 'Los neutrinos tienen masa',
    subtitle: 'Por el descubrimiento de las oscilaciones de los neutrinos, que muestran que los neutrinos tienen masa.',
    impact: 'Los neutrinos se transforman entre sí — eso requiere que tengan masa, contra el Modelo Estándar puro. Física más allá del modelo.',
    status: 'pending',
  },

  // ═══════════════════════ NÚCLEO ATÓMICO ═══════════════════════
  {
    id: 'phys-1903-radioactivity',
    year: 1903,
    laureates: ['Henri Becquerel', 'Pierre Curie', 'Marie Curie'],
    block: 'nucleo',
    title: 'Radiactividad: el primer Nobel compartido',
    subtitle: 'Becquerel: por el descubrimiento de la radiactividad espontánea. Marie y Pierre Curie: por sus investigaciones conjuntas sobre los fenómenos de radiación descubiertos por Becquerel.',
    impact: 'Becquerel descubrió que el uranio emite "algo" por sí solo. Marie Curie acuñó "radiactividad" y aisló el polonio y el radio. La primera mujer Nobel.',
    status: 'pending',
  },
  {
    id: 'phys-1935-chadwick',
    year: 1935,
    laureates: ['James Chadwick'],
    block: 'nucleo',
    title: 'El neutrón',
    subtitle: 'Por el descubrimiento del neutrón.',
    impact: 'En 1932 detectó la partícula que sostiene los núcleos sin carga. Hizo posible la fisión, la bomba, y la energía nuclear.',
    status: 'pending',
  },
  {
    id: 'phys-1938-fermi',
    year: 1938,
    laureates: ['Enrico Fermi'],
    block: 'nucleo',
    title: 'Fermi y la radiactividad inducida',
    subtitle: 'Por sus demostraciones de la existencia de nuevos elementos radiactivos producidos por irradiación de neutrones, y por el descubrimiento de reacciones nucleares con neutrones lentos.',
    impact: 'Construyó el primer reactor nuclear en Chicago en 1942. Recogió el Nobel y huyó de la Italia fascista directo a EE.UU. en el mismo viaje.',
    status: 'pending',
  },
  {
    id: 'phys-1939-lawrence',
    year: 1939,
    laureates: ['Ernest Lawrence'],
    block: 'nucleo',
    title: 'El ciclotrón',
    subtitle: 'Por la invención y el desarrollo del ciclotrón y los resultados obtenidos.',
    impact: 'Inventó el primer acelerador circular de partículas. Berkeley fue el centro del mundo en física nuclear durante 30 años por él.',
    status: 'pending',
  },
  {
    id: 'phys-1943-stern',
    year: 1943,
    laureates: ['Otto Stern'],
    block: 'nucleo',
    title: 'El momento magnético del protón',
    subtitle: 'Por su contribución al desarrollo del método molecular de rayos y su descubrimiento del momento magnético del protón.',
    impact: 'Stern-Gerlach: demostró que el espín está cuantizado, no es continuo. Uno de los experimentos más bellos del siglo XX.',
    status: 'pending',
  },
  {
    id: 'phys-1944-rabi',
    year: 1944,
    laureates: ['Isidor Isaac Rabi'],
    block: 'nucleo',
    title: 'Resonancia magnética nuclear',
    subtitle: 'Por su método de resonancia para registrar las propiedades magnéticas de los núcleos atómicos.',
    impact: 'La técnica que después se convirtió en la resonancia magnética del hospital. Empezó en un haz molecular en Columbia.',
    status: 'pending',
  },
  {
    id: 'phys-1948-blackett',
    year: 1948,
    laureates: ['Patrick Blackett'],
    block: 'nucleo',
    title: 'La cámara de niebla mejorada',
    subtitle: 'Por su desarrollo del método de Wilson de la cámara de niebla, y sus descubrimientos en física nuclear y radiación cósmica.',
    impact: 'Perfeccionó la cámara que ve trayectorias subatómicas. Mostró pares electrón-positrón formándose de pura energía — E=mc² en directo.',
    status: 'pending',
  },
  {
    id: 'phys-1951-cockcroft-walton',
    year: 1951,
    laureates: ['John Cockcroft', 'Ernest Walton'],
    block: 'nucleo',
    title: 'La primera transmutación artificial',
    subtitle: 'Por su trabajo pionero sobre la transmutación de núcleos atómicos mediante partículas atómicas aceleradas artificialmente.',
    impact: 'En 1932 dividieron un núcleo de litio con un acelerador. Por primera vez los humanos partimos átomos a voluntad.',
    status: 'pending',
  },
  {
    id: 'phys-1952-bloch-purcell',
    year: 1952,
    laureates: ['Felix Bloch', 'Edward Purcell'],
    block: 'nucleo',
    title: 'NMR en líquidos y sólidos',
    subtitle: 'Por el desarrollo de nuevos métodos para mediciones nucleares de precisión y los descubrimientos resultantes.',
    impact: 'Tomaron la NMR de Rabi y la llevaron a materia condensada. Cada hospital del mundo usa hoy esta técnica.',
    status: 'pending',
  },
  {
    id: 'phys-1961-hofstadter-mossbauer',
    year: 1961,
    laureates: ['Robert Hofstadter', 'Rudolf Mössbauer'],
    block: 'nucleo',
    title: 'La estructura del nucleón y el efecto Mössbauer',
    subtitle: 'Hofstadter: por estudios pioneros de dispersión de electrones en núcleos atómicos. Mössbauer: por sus investigaciones sobre absorción resonante de radiación gamma.',
    impact: 'Hofstadter midió el tamaño del protón. Mössbauer descubrió cómo un núcleo entero puede absorber gamma sin retroceso — relojería de altísima precisión.',
    status: 'pending',
  },
  {
    id: 'phys-1962-landau',
    year: 1962,
    laureates: ['Lev Landau'],
    block: 'superconductividad-superfluidos',
    title: 'Superfluidez del helio líquido',
    subtitle: 'Por sus teorías pioneras sobre la materia condensada, especialmente el helio líquido.',
    impact: 'El físico teórico más influyente de la URSS. Su tratado de 10 tomos es lectura obligatoria. El Nobel se lo entregaron en el hospital tras un accidente.',
    status: 'pending',
  },
  {
    id: 'phys-1975-bohr-mottelson-rainwater',
    year: 1975,
    laureates: ['Aage Bohr', 'Ben Mottelson', 'James Rainwater'],
    block: 'nucleo',
    title: 'El núcleo deformado',
    subtitle: 'Por el descubrimiento de la conexión entre el movimiento colectivo y el movimiento de partículas individuales en los núcleos atómicos.',
    impact: 'Los núcleos no son bolitas perfectas — vibran, rotan, se deforman. Aage Bohr era hijo de Niels — el segundo Nobel familiar Bohr.',
    status: 'pending',
  },

  // ═══════════════════════ COSMOLOGÍA Y ASTROFÍSICA ═══════════════════════
  {
    id: 'phys-1967-bethe',
    year: 1967,
    laureates: ['Hans Bethe'],
    block: 'cosmologia-astrofisica',
    title: 'Cómo brillan las estrellas',
    subtitle: 'Por sus contribuciones a la teoría de las reacciones nucleares, especialmente sus descubrimientos sobre la producción de energía en las estrellas.',
    impact: 'En 1939 resolvió el misterio de por qué arden las estrellas: ciclo CNO y cadena protón-protón. La fusión que nos da el sol.',
    status: 'pending',
  },
  {
    id: 'phys-1974-ryle-hewish',
    year: 1974,
    laureates: ['Martin Ryle', 'Antony Hewish'],
    block: 'cosmologia-astrofisica',
    title: 'Radio-astronomía y púlsares',
    subtitle: 'Por investigaciones pioneras en radio-astrofísica: técnicas de apertura sintética (Ryle) y descubrimiento de los púlsares (Hewish).',
    impact: 'Quien realmente descubrió los pulsares fue Jocelyn Bell, su estudiante. El Nobel se lo dieron a su director — escándalo histórico de la astrofísica.',
    status: 'pending',
  },
  {
    id: 'phys-1978-kapitsa-cmb',
    year: 1978,
    laureates: ['Pyotr Kapitsa', 'Arno Penzias', 'Robert Wilson'],
    block: 'cosmologia-astrofisica',
    title: 'El eco del Big Bang',
    subtitle: 'Kapitsa: por descubrimientos en física a bajas temperaturas. Penzias y Wilson: por el descubrimiento de la radiación cósmica de fondo.',
    impact: 'Penzias y Wilson creyeron que era ruido de palomas en la antena. Lo limpiaron, midieron y descubrieron el resplandor del universo a 380 mil años de edad.',
    status: 'pending',
  },
  {
    id: 'phys-1983-chandrasekhar-fowler',
    year: 1983,
    laureates: ['Subrahmanyan Chandrasekhar', 'William Fowler'],
    block: 'cosmologia-astrofisica',
    title: 'El límite de Chandrasekhar y la nucleosíntesis estelar',
    subtitle: 'Chandrasekhar: por estudios teóricos de la estructura y evolución de las estrellas. Fowler: por estudios teóricos y experimentales sobre las reacciones nucleares que producen los elementos.',
    impact: 'Chandrasekhar demostró que una enana blanca con más de 1.4 masas solares colapsa. Fowler explicó de dónde vienen el carbono y oro de tu cuerpo.',
    status: 'pending',
  },
  {
    id: 'phys-2002-neutrinos-xray',
    year: 2002,
    laureates: ['Raymond Davis', 'Masatoshi Koshiba', 'Riccardo Giacconi'],
    block: 'cosmologia-astrofisica',
    title: 'Astronomía con neutrinos y rayos X',
    subtitle: 'Davis y Koshiba: por contribuciones pioneras a la astrofísica, en particular la detección de neutrinos cósmicos. Giacconi: por contribuciones a la astronomía de rayos X.',
    impact: 'Davis detectó los primeros neutrinos solares en un tanque de tetracloroeteno en una mina. Koshiba detectó la supernova 1987A. Giacconi descubrió fuentes X en el cielo.',
    status: 'pending',
  },
  {
    id: 'phys-2006-cobe',
    year: 2006,
    laureates: ['John Mather', 'George Smoot'],
    block: 'cosmologia-astrofisica',
    title: 'COBE: la foto del bebé universo',
    subtitle: 'Por su descubrimiento de la forma de cuerpo negro y la anisotropía de la radiación cósmica de fondo.',
    impact: 'El satélite COBE midió fluctuaciones diminutas en el CMB — las semillas de todas las galaxias del universo.',
    status: 'pending',
  },
  {
    id: 'phys-2011-dark-energy',
    year: 2011,
    laureates: ['Saul Perlmutter', 'Brian Schmidt', 'Adam Riess'],
    block: 'cosmologia-astrofisica',
    title: 'El universo acelera — energía oscura',
    subtitle: 'Por el descubrimiento de la expansión acelerada del Universo a través de observaciones de supernovas distantes.',
    impact: 'Esperaban encontrar que el universo se frena. Encontraron que acelera. 70% del universo es algo que aún no entendemos.',
    status: 'pending',
  },
  {
    id: 'phys-2019-peebles-mayor-queloz',
    year: 2019,
    laureates: ['James Peebles', 'Michel Mayor', 'Didier Queloz'],
    block: 'cosmologia-astrofisica',
    title: 'Cosmología teórica y el primer exoplaneta',
    subtitle: 'Peebles: por descubrimientos teóricos en cosmología física. Mayor y Queloz: por el descubrimiento de un exoplaneta orbitando una estrella tipo solar.',
    impact: 'Peebles construyó el marco teórico Lambda-CDM. Mayor y Queloz encontraron 51 Pegasi b en 1995 — el primero de los miles de mundos fuera del sistema solar.',
    status: 'pending',
  },

  // ═══════════════════════ SUPERCONDUCTIVIDAD Y SUPERFLUIDOS ═══════════════════════
  {
    id: 'phys-1913-onnes',
    year: 1913,
    laureates: ['Heike Kamerlingh Onnes'],
    block: 'superconductividad-superfluidos',
    title: 'Superconductividad: descubierta por accidente',
    subtitle: 'Por sus investigaciones sobre las propiedades de la materia a bajas temperaturas, que entre otras cosas llevó a la producción de helio líquido.',
    impact: 'Enfrió mercurio a 4 K y la resistencia cayó a cero. No la cero medible — cero verdadera. Costó 50 años entender por qué.',
    status: 'pending',
  },
  {
    id: 'phys-1972-bcs',
    year: 1972,
    laureates: ['John Bardeen', 'Leon Cooper', 'John Schrieffer'],
    block: 'superconductividad-superfluidos',
    title: 'La teoría BCS de la superconductividad',
    subtitle: 'Por su teoría desarrollada conjuntamente de la superconductividad, llamada teoría BCS.',
    impact: 'Bardeen ya tenía un Nobel (por el transistor). Es el único físico que ha ganado DOS Nobeles de Física. Cooper inventó los pares.',
    status: 'pending',
  },
  {
    id: 'phys-1973-tunneling',
    year: 1973,
    laureates: ['Leo Esaki', 'Ivar Giaever', 'Brian Josephson'],
    block: 'superconductividad-superfluidos',
    title: 'Efecto túnel — clásico y cuántico',
    subtitle: 'Esaki y Giaever: descubrimientos experimentales sobre fenómenos de tunelaje. Josephson: predicción teórica de propiedades de una supercorriente.',
    impact: 'Josephson predijo a los 22 años un efecto fundamental. La unión Josephson es hoy la base de los qubits superconductores.',
    status: 'pending',
  },
  {
    id: 'phys-1987-bednorz-muller',
    year: 1987,
    laureates: ['Johannes Bednorz', 'Karl Müller'],
    block: 'superconductividad-superfluidos',
    title: 'Superconductividad de alta temperatura',
    subtitle: 'Por su importante descubrimiento de la superconductividad en materiales cerámicos.',
    impact: 'En 1986 encontraron cerámicos que superconducen a 35 K — el doble del récord previo. Nobel a los pocos meses, el más rápido de la historia.',
    status: 'pending',
  },
  {
    id: 'phys-1996-helium3',
    year: 1996,
    laureates: ['David Lee', 'Douglas Osheroff', 'Robert Richardson'],
    block: 'superconductividad-superfluidos',
    title: 'Superfluidez del helio-3',
    subtitle: 'Por su descubrimiento de la superfluidez en el helio-3.',
    impact: 'Mientras buscaban algo más, Osheroff (estudiante de doctorado) descubrió un nuevo estado cuántico de la materia a temperatura un milésimo sobre cero absoluto.',
    status: 'pending',
  },
  {
    id: 'phys-2003-ginzburg-leggett',
    year: 2003,
    laureates: ['Alexei Abrikosov', 'Vitaly Ginzburg', 'Anthony Leggett'],
    block: 'superconductividad-superfluidos',
    title: 'Teorías de superconductividad y superfluidos',
    subtitle: 'Por contribuciones pioneras a la teoría de superconductores y superfluidos.',
    impact: 'Ginzburg-Landau es la ecuación maestra. Abrikosov predijo los vórtices que llevan su nombre. Leggett explicó el helio-3 superfluido.',
    status: 'pending',
  },

  // ═══════════════════════ MATERIA CONDENSADA ═══════════════════════
  {
    id: 'phys-1910-vanderwaals',
    year: 1910,
    laureates: ['Johannes Diderik van der Waals'],
    block: 'materia-condensada',
    title: 'La ecuación de van der Waals',
    subtitle: 'Por su trabajo sobre la ecuación de estado de gases y líquidos.',
    impact: 'La primera ecuación que explicaba por qué los gases reales no son ideales. Su nombre está hoy en las fuerzas que hacen pegar al gecko.',
    status: 'pending',
  },
  {
    id: 'phys-1970-alfven-neel',
    year: 1970,
    laureates: ['Hannes Alfvén', 'Louis Néel'],
    block: 'materia-condensada',
    title: 'Magnetohidrodinámica y antiferromagnetismo',
    subtitle: 'Alfvén: por trabajo fundamental en magnetohidrodinámica con aplicaciones en plasma. Néel: por descubrimientos del antiferromagnetismo y ferrimagnetismo.',
    impact: 'Alfvén: el plasma cósmico tiene "ondas de Alfvén" — base de la física solar. Néel: explicó por qué algunos materiales magnéticos cancelan sus campos por dentro.',
    status: 'pending',
  },
  {
    id: 'phys-1977-anderson-mott',
    year: 1977,
    laureates: ['Philip Anderson', 'Nevill Mott', 'John Van Vleck'],
    block: 'materia-condensada',
    title: 'Localización y transiciones aislante-conductor',
    subtitle: 'Por investigaciones teóricas fundamentales sobre la estructura electrónica de los sistemas magnéticos y desordenados.',
    impact: 'Anderson: "More is different" — el ensayo más citado de filosofía de la física. La emergencia es real.',
    status: 'pending',
  },
  {
    id: 'phys-1982-wilson',
    year: 1982,
    laureates: ['Kenneth Wilson'],
    block: 'materia-condensada',
    title: 'Grupo de renormalización y transiciones de fase',
    subtitle: 'Por su teoría sobre los fenómenos críticos en relación con las transiciones de fase.',
    impact: 'Inventó el método para entender cómo cambia un sistema cuando lo miras a distintas escalas. Aplicable desde imanes hasta cosmología y machine learning.',
    status: 'pending',
  },
  {
    id: 'phys-1985-vonklitzing',
    year: 1985,
    laureates: ['Klaus von Klitzing'],
    block: 'materia-condensada',
    title: 'Efecto Hall cuántico',
    subtitle: 'Por el descubrimiento del efecto Hall cuantizado.',
    impact: 'Encontró un cuanto de resistencia eléctrica — h/e² — exacto a 9 decimales. Hoy define la unidad SI del ohmio.',
    status: 'pending',
  },
  {
    id: 'phys-1991-degennes',
    year: 1991,
    laureates: ['Pierre-Gilles de Gennes'],
    block: 'materia-condensada',
    title: 'La física de la materia blanda',
    subtitle: 'Por descubrir que métodos para estudiar fenómenos de orden en sistemas simples pueden generalizarse a formas de materia más complejas, en particular cristales líquidos y polímeros.',
    impact: 'El "Newton de la materia blanda". Llevó la física a las pantallas LCD, los geles, las gomas. Comunicador genial — escribió libros para niños.',
    status: 'pending',
  },
  {
    id: 'phys-1994-brockhouse-shull',
    year: 1994,
    laureates: ['Bertram Brockhouse', 'Clifford Shull'],
    block: 'materia-condensada',
    title: 'Dispersión de neutrones',
    subtitle: 'Por contribuciones pioneras al desarrollo de técnicas de dispersión de neutrones para estudios de materia condensada.',
    impact: 'Los neutrones son la luz perfecta para ver átomos: penetran profundo y sienten el magnetismo. Cada laboratorio de neutrones del mundo usa su método.',
    status: 'pending',
  },
  {
    id: 'phys-1998-fqhe',
    year: 1998,
    laureates: ['Robert Laughlin', 'Horst Störmer', 'Daniel Tsui'],
    block: 'materia-condensada',
    title: 'Efecto Hall cuántico fraccionario',
    subtitle: 'Por el descubrimiento de una nueva forma de fluido cuántico con excitaciones de carga fraccionaria.',
    impact: 'Electrones que se comportan como partículas con carga 1/3 del electrón. La función de onda de Laughlin sigue siendo una de las más bellas de la física.',
    status: 'pending',
  },
  {
    id: 'phys-2007-gmr',
    year: 2007,
    laureates: ['Albert Fert', 'Peter Grünberg'],
    block: 'materia-condensada',
    title: 'Magnetorresistencia gigante (GMR)',
    subtitle: 'Por el descubrimiento de la magnetorresistencia gigante.',
    impact: 'El efecto que hizo posibles los discos duros modernos de Terabytes. La spintrónica nació aquí.',
    status: 'pending',
  },
  {
    id: 'phys-2010-graphene',
    year: 2010,
    laureates: ['Andre Geim', 'Konstantin Novoselov'],
    block: 'materia-condensada',
    title: 'Grafeno: el material de una sola capa',
    subtitle: 'Por experimentos innovadores con el material bidimensional grafeno.',
    impact: 'Lo aislaron con cinta adhesiva sobre un cristal de grafito. Más fuerte que el acero, más conductor que el cobre. Geim también ganó el Ig Nobel — hizo levitar una rana.',
    status: 'pending',
  },
  {
    id: 'phys-2016-topological',
    year: 2016,
    laureates: ['David Thouless', 'Duncan Haldane', 'John Michael Kosterlitz'],
    block: 'materia-condensada',
    title: 'Fases topológicas de la materia',
    subtitle: 'Por descubrimientos teóricos sobre transiciones de fase topológicas y fases topológicas de la materia.',
    impact: 'La topología — la matemática de las donas vs las tazas — ahora clasifica estados de la materia. Aisladores topológicos: el futuro del cómputo cuántico.',
    status: 'pending',
  },

  // ═══════════════════════ SEMICONDUCTORES Y ELECTRÓNICA ═══════════════════════
  {
    id: 'phys-1956-transistor',
    year: 1956,
    laureates: ['William Shockley', 'John Bardeen', 'Walter Brattain'],
    block: 'semiconductores-electronica',
    title: 'El transistor: el invento del siglo',
    subtitle: 'Por sus investigaciones sobre semiconductores y su descubrimiento del efecto transistor.',
    impact: 'En Bell Labs en 1947 inventaron lo que hoy hay en cada chip. Sin transistor, sin computadoras, sin internet, sin esta clase.',
    status: 'pending',
  },
  {
    id: 'phys-2000-heterostructures',
    year: 2000,
    laureates: ['Zhores Alferov', 'Herbert Kroemer', 'Jack Kilby'],
    block: 'semiconductores-electronica',
    title: 'Heteroestructuras y el chip integrado',
    subtitle: 'Alferov y Kroemer: por desarrollar heteroestructuras semiconductoras usadas en electrónica de alta velocidad y opto-electrónica. Kilby: por su parte en la invención del circuito integrado.',
    impact: 'Kilby construyó el primer chip integrado en Texas Instruments en 1958. Alferov y Kroemer hicieron posibles los láseres de los DVDs y la fibra óptica.',
    status: 'pending',
  },
  {
    id: 'phys-2009-fiber-ccd',
    year: 2009,
    laureates: ['Charles Kao', 'Willard Boyle', 'George Smith'],
    block: 'semiconductores-electronica',
    title: 'Fibra óptica y el sensor CCD',
    subtitle: 'Kao: por logros pioneros en transmisión de luz en fibras para comunicación óptica. Boyle y Smith: por la invención del sensor CCD.',
    impact: 'Kao calculó la pureza necesaria para fibras de internet — el internet entero corre sobre su intuición. Boyle/Smith inventaron el sensor de tu cámara.',
    status: 'pending',
  },
  {
    id: 'phys-2014-blue-led',
    year: 2014,
    laureates: ['Isamu Akasaki', 'Hiroshi Amano', 'Shuji Nakamura'],
    block: 'semiconductores-electronica',
    title: 'El LED azul: el último color que faltaba',
    subtitle: 'Por la invención de diodos emisores de luz azul eficientes, que han hecho posibles fuentes de luz blanca brillantes y eficientes en energía.',
    impact: 'El LED rojo y verde llegaron en los 60s. El azul tardó 30 años más. Sin él, no hay LED blanco, no hay pantallas modernas, no hay focos eficientes.',
    status: 'pending',
  },

  // ═══════════════════════ ÓPTICA Y LÁSERES ═══════════════════════
  {
    id: 'phys-1907-michelson',
    year: 1907,
    laureates: ['Albert Michelson'],
    block: 'optica-laseres',
    title: 'El interferómetro que midió la luz',
    subtitle: 'Por sus instrumentos ópticos de precisión y las investigaciones espectroscópicas y metrológicas realizadas con ellos.',
    impact: 'Construyó el aparato para medir la velocidad de la luz con precisión. Y descubrió, sin querer, que no hay éter — sembrando la relatividad de Einstein.',
    status: 'pending',
  },
  {
    id: 'phys-1908-lippmann',
    year: 1908,
    laureates: ['Gabriel Lippmann'],
    block: 'optica-laseres',
    title: 'La fotografía a color por interferencia',
    subtitle: 'Por su método de reproducir colores fotográficamente basado en el fenómeno de la interferencia.',
    impact: 'Inventó un método para grabar TODO el espectro en una placa fotográfica usando interferencia. Hermoso, lento, comercialmente fallido — pero teóricamente perfecto.',
    status: 'pending',
  },
  {
    id: 'phys-1953-zernike',
    year: 1953,
    laureates: ['Frits Zernike'],
    block: 'optica-laseres',
    title: 'El microscopio de contraste de fase',
    subtitle: 'Por su demostración del método de contraste de fase, especialmente por su invención del microscopio de contraste de fase.',
    impact: 'Permitió ver células vivas sin teñirlas. Toda la biología celular moderna empezó por este microscopio.',
    status: 'pending',
  },
  {
    id: 'phys-1964-maser-laser',
    year: 1964,
    laureates: ['Charles Townes', 'Nikolay Basov', 'Aleksandr Prokhorov'],
    block: 'optica-laseres',
    title: 'El máser y el láser',
    subtitle: 'Por trabajo fundamental en electrónica cuántica que llevó a la construcción de osciladores y amplificadores basados en el principio máser-láser.',
    impact: 'Townes pensó en el máser sentado en un parque de Washington a las 6 de la mañana. Hoy: cada lector de CDs, cada cirugía ocular, cada fibra óptica.',
    status: 'pending',
  },
  {
    id: 'phys-1966-kastler',
    year: 1966,
    laureates: ['Alfred Kastler'],
    block: 'optica-laseres',
    title: 'Bombeo óptico',
    subtitle: 'Por el descubrimiento y desarrollo de métodos ópticos para estudiar resonancias hertzianas en átomos.',
    impact: 'Inventó el bombeo óptico — usar luz para poner átomos en estados específicos. La base de los relojes atómicos y muchos láseres.',
    status: 'pending',
  },
  {
    id: 'phys-1971-gabor',
    year: 1971,
    laureates: ['Dennis Gabor'],
    block: 'optica-laseres',
    title: 'Holografía',
    subtitle: 'Por su invención y desarrollo del método holográfico.',
    impact: 'Inventó la holografía en 1947, pero hasta que llegó el láser (1960) nadie podía hacerla. Tu billete de banco tiene holografías por él.',
    status: 'pending',
  },
  {
    id: 'phys-1981-laser-spec',
    year: 1981,
    laureates: ['Nicolaas Bloembergen', 'Arthur Schawlow', 'Kai Siegbahn'],
    block: 'optica-laseres',
    title: 'Espectroscopía láser y espectroscopía electrónica',
    subtitle: 'Bloembergen y Schawlow: por contribuciones al desarrollo de espectroscopía láser. K. Siegbahn: por contribuciones al desarrollo de espectroscopía electrónica de alta resolución.',
    impact: 'Mediciones de átomos con láser tan precisas que cambiaron el cgs y la métrica. K. Siegbahn — hijo de Manne Siegbahn (Nobel 1924).',
    status: 'pending',
  },
  {
    id: 'phys-1997-laser-cooling',
    year: 1997,
    laureates: ['Steven Chu', 'Claude Cohen-Tannoudji', 'William Phillips'],
    block: 'optica-laseres',
    title: 'Enfriamiento de átomos con láser',
    subtitle: 'Por el desarrollo de métodos para enfriar y atrapar átomos con luz láser.',
    impact: 'Lograron temperaturas de millonésimas de Kelvin disparando láseres a átomos. Chu después fue Secretario de Energía de Obama.',
    status: 'pending',
  },
  {
    id: 'phys-2001-bec',
    year: 2001,
    laureates: ['Eric Cornell', 'Wolfgang Ketterle', 'Carl Wieman'],
    block: 'optica-laseres',
    title: 'Condensado de Bose-Einstein',
    subtitle: 'Por el logro de la condensación de Bose-Einstein en gases diluidos de átomos alcalinos.',
    impact: 'Crearon en 1995 un estado de la materia predicho por Einstein en 1924. Todos los átomos en el MISMO estado cuántico — visible al microscopio.',
    status: 'pending',
  },
  {
    id: 'phys-2005-glauber-hall-hansch',
    year: 2005,
    laureates: ['Roy Glauber', 'John Hall', 'Theodor Hänsch'],
    block: 'optica-laseres',
    title: 'Óptica cuántica y peines de frecuencia',
    subtitle: 'Glauber: por su contribución a la teoría cuántica de la coherencia óptica. Hall y Hänsch: por el desarrollo de espectroscopía láser de precisión y la técnica del peine óptico.',
    impact: 'Hall y Hänsch convirtieron el láser en una regla de tiempo. Cada GPS preciso usa esta tecnología.',
    status: 'pending',
  },
  {
    id: 'phys-2018-tweezers-cpa',
    year: 2018,
    laureates: ['Arthur Ashkin', 'Gérard Mourou', 'Donna Strickland'],
    block: 'optica-laseres',
    title: 'Pinzas ópticas y amplificación de pulsos chirped',
    subtitle: 'Ashkin: por las pinzas ópticas y su aplicación a sistemas biológicos. Mourou y Strickland: por su método para generar pulsos ópticos ultracortos de alta intensidad.',
    impact: 'Ashkin: atrapar una bacteria con un rayo de luz. Strickland: tercera mujer Nobel de Física en la historia. Mourou-Strickland: la cirugía láser ocular.',
    status: 'pending',
  },

  // ═══════════════════════ TÉCNICAS EXPERIMENTALES ═══════════════════════
  {
    id: 'phys-1904-rayleigh',
    year: 1904,
    laureates: ['Lord Rayleigh'],
    block: 'tecnicas-experimentales',
    title: 'La densidad del aire y el descubrimiento del argón',
    subtitle: 'Por sus investigaciones de las densidades de los gases más importantes y por el descubrimiento del argón.',
    impact: 'Midiendo gases con precisión obsesiva, encontró un gas inerte que nadie había visto: el argón. La precisión obsesiva paga.',
    status: 'pending',
  },
  {
    id: 'phys-1909-marconi-braun',
    year: 1909,
    laureates: ['Guglielmo Marconi', 'Ferdinand Braun'],
    block: 'tecnicas-experimentales',
    title: 'Radio: la comunicación inalámbrica',
    subtitle: 'En reconocimiento por sus contribuciones al desarrollo de la telegrafía inalámbrica.',
    impact: 'Marconi cruzó el Atlántico con una señal en 1901. Braun inventó el tubo de rayos catódicos — la TV antes de las pantallas LCD.',
    status: 'pending',
  },
  {
    id: 'phys-1911-wien',
    year: 1911,
    laureates: ['Wilhelm Wien'],
    block: 'tecnicas-experimentales',
    title: 'La ley de Wien y la radiación del cuerpo negro',
    subtitle: 'Por sus descubrimientos sobre las leyes que rigen la radiación del calor.',
    impact: 'Demostró que λ_máx · T = constante. La pista que llevó a Planck a inventar el cuanto cinco años después.',
    status: 'pending',
  },
  {
    id: 'phys-1926-perrin',
    year: 1926,
    laureates: ['Jean Perrin'],
    block: 'tecnicas-experimentales',
    title: 'Movimiento browniano: la prueba final de los átomos',
    subtitle: 'Por su trabajo sobre la estructura discontinua de la materia, y especialmente por su descubrimiento del equilibrio de sedimentación.',
    impact: 'Confirmó experimentalmente la predicción de Einstein de 1905 — los átomos existen. Los anti-atomistas se quedaron sin argumentos.',
    status: 'pending',
  },
  {
    id: 'phys-1901-rontgen',
    year: 1901,
    laureates: ['Wilhelm Röntgen'],
    block: 'tecnicas-experimentales',
    title: 'Los rayos X — el primer Nobel',
    subtitle: 'En reconocimiento de los extraordinarios servicios que ha prestado mediante el descubrimiento de los notables rayos que posteriormente fueron nombrados en su honor.',
    impact: 'El primer Nobel de Física. Descubrió que su esposa tenía huesos visibles. La radiología nació esa noche.',
    status: 'pending',
  },
  {
    id: 'phys-1902-lorentz-zeeman',
    year: 1902,
    laureates: ['Hendrik Lorentz', 'Pieter Zeeman'],
    block: 'tecnicas-experimentales',
    title: 'El efecto Zeeman',
    subtitle: 'En reconocimiento por el extraordinario servicio que han prestado con sus investigaciones sobre la influencia del magnetismo en los fenómenos radiantes.',
    impact: 'Demostraron que un campo magnético divide las rayas espectrales. Lorentz dio la teoría — su transformación es la base de la relatividad.',
    status: 'pending',
  },
  {
    id: 'phys-1905-lenard',
    year: 1905,
    laureates: ['Philipp Lenard'],
    block: 'tecnicas-experimentales',
    title: 'Rayos catódicos y el efecto fotoeléctrico',
    subtitle: 'Por su trabajo sobre los rayos catódicos.',
    impact: 'Demostró que los rayos catódicos atraviesan delgadas láminas metálicas. Sus experimentos sobre el efecto fotoeléctrico dieron datos clave a Einstein.',
    status: 'pending',
  },
  {
    id: 'phys-1906-jjthomson',
    year: 1906,
    laureates: ['J.J. Thomson'],
    block: 'tecnicas-experimentales',
    title: 'El descubrimiento del electrón',
    subtitle: 'En reconocimiento de los grandes méritos de sus investigaciones teóricas y experimentales sobre la conducción de electricidad por gases.',
    impact: 'En 1897 demostró que los rayos catódicos eran partículas con carga negativa más ligeras que el átomo. La primera partícula subatómica.',
    status: 'pending',
  },
  {
    id: 'phys-1914-vonlaue',
    year: 1914,
    laureates: ['Max von Laue'],
    block: 'tecnicas-experimentales',
    title: 'Difracción de rayos X en cristales',
    subtitle: 'Por su descubrimiento de la difracción de rayos X por cristales.',
    impact: 'Demostró que los cristales son rejillas tridimensionales — y que los rayos X son ondas. Base de toda la cristalografía moderna.',
    status: 'pending',
  },
  {
    id: 'phys-1915-bragg-bragg',
    year: 1915,
    laureates: ['William Henry Bragg', 'William Lawrence Bragg'],
    block: 'tecnicas-experimentales',
    title: 'Estructura cristalina con rayos X',
    subtitle: 'Por sus servicios en el análisis de la estructura cristalina por medio de rayos X.',
    impact: 'Padre e hijo. Lawrence Bragg ganó a los 25 años — el Nobel más joven. La fórmula nλ = 2d sin θ resuelve cualquier cristal.',
    status: 'pending',
  },
  {
    id: 'phys-1923-millikan',
    year: 1923,
    laureates: ['Robert Millikan'],
    block: 'tecnicas-experimentales',
    title: 'La carga elemental — gotas de aceite',
    subtitle: 'Por su trabajo sobre la carga elemental de electricidad y el efecto fotoeléctrico.',
    impact: 'Midió la carga del electrón observando gotas de aceite electrizadas. El experimento más famoso de física aplicada.',
    status: 'pending',
  },
  {
    id: 'phys-1927-compton-wilson',
    year: 1927,
    laureates: ['Arthur Compton', 'C.T.R. Wilson'],
    block: 'tecnicas-experimentales',
    title: 'Efecto Compton y la cámara de niebla',
    subtitle: 'Compton: por su descubrimiento del efecto que lleva su nombre. Wilson: por su método para hacer visibles las trayectorias de partículas cargadas mediante la condensación de vapor.',
    impact: 'Compton demostró que los rayos X chocan como partículas — confirmación definitiva del fotón. Wilson hizo "visibles" las partículas.',
    status: 'pending',
  },
  {
    id: 'phys-1928-richardson',
    year: 1928,
    laureates: ['Owen Willans Richardson'],
    block: 'tecnicas-experimentales',
    title: 'Emisión termoiónica — el efecto Richardson',
    subtitle: 'Por su trabajo sobre el fenómeno termoiónico, especialmente por el descubrimiento de la ley que lleva su nombre.',
    impact: 'Demostró que los metales calientes emiten electrones — base de los tubos de vacío y de toda la electrónica antes del transistor.',
    status: 'pending',
  },
  {
    id: 'phys-1930-raman',
    year: 1930,
    laureates: ['Chandrasekhara Venkata Raman'],
    block: 'tecnicas-experimentales',
    title: 'El efecto Raman',
    subtitle: 'Por su trabajo sobre la dispersión de la luz y por el descubrimiento del efecto que lleva su nombre.',
    impact: 'Primer Nobel asiático en ciencias. La espectroscopía Raman se usa hoy desde diagnósticos médicos hasta detección de explosivos en aeropuertos.',
    status: 'pending',
  },
  {
    id: 'phys-1937-davisson-thomson',
    year: 1937,
    laureates: ['Clinton Davisson', 'George Paget Thomson'],
    block: 'tecnicas-experimentales',
    title: 'Los electrones difractan',
    subtitle: 'Por su descubrimiento experimental de la difracción de electrones por cristales.',
    impact: 'Confirmaron experimentalmente las ondas de de Broglie. G.P. Thomson era hijo de J.J. Thomson — el papá ganó probando que era partícula, el hijo probando que era onda.',
    status: 'pending',
  },
  {
    id: 'phys-1958-cherenkov',
    year: 1958,
    laureates: ['Pavel Cherenkov', 'Ilya Frank', 'Igor Tamm'],
    block: 'tecnicas-experimentales',
    title: 'El efecto Cherenkov: el brillo azul',
    subtitle: 'Por el descubrimiento y la interpretación del efecto Cherenkov.',
    impact: 'La luz azul de las piscinas de reactores nucleares — partículas yendo más rápido que la luz EN EL AGUA. Detector clave en física de neutrinos.',
    status: 'pending',
  },
  {
    id: 'phys-1960-glaser',
    year: 1960,
    laureates: ['Donald Glaser'],
    block: 'tecnicas-experimentales',
    title: 'La cámara de burbujas',
    subtitle: 'Por la invención de la cámara de burbujas.',
    impact: 'Mientras observaba la cerveza, se le ocurrió: un líquido sobrecalentado deja burbujas al paso de partículas. Reemplazó a la cámara de niebla.',
    status: 'pending',
  },
  {
    id: 'phys-1968-alvarez',
    year: 1968,
    laureates: ['Luis Walter Alvarez'],
    block: 'tecnicas-experimentales',
    title: 'Estados de resonancia y la dinastía Alvarez',
    subtitle: 'Por sus contribuciones decisivas a la física de partículas elementales, particularmente el descubrimiento de un gran número de estados de resonancia, gracias a su desarrollo de la cámara de burbujas con hidrógeno y al análisis de datos.',
    impact: 'Aparte de eso, propuso con su hijo la hipótesis del asteroide que mató a los dinosaurios. Un solo cerebro: dos campos transformados.',
    status: 'pending',
  },
  {
    id: 'phys-1986-ruska-stm',
    year: 1986,
    laureates: ['Ernst Ruska', 'Gerd Binnig', 'Heinrich Rohrer'],
    block: 'tecnicas-experimentales',
    title: 'Microscopio electrónico y microscopio de túnel',
    subtitle: 'Ruska: por el diseño del primer microscopio electrónico. Binnig y Rohrer: por su diseño del microscopio de barrido por efecto túnel (STM).',
    impact: 'Binnig y Rohrer inventaron en 1981 cómo "tocar" átomos individuales — efecto túnel a la mano. Hoy: nanotecnología.',
    status: 'pending',
  },
  {
    id: 'phys-1992-charpak',
    year: 1992,
    laureates: ['Georges Charpak'],
    block: 'tecnicas-experimentales',
    title: 'Cámara proporcional multihilo',
    subtitle: 'Por su invención y desarrollo de detectores de partículas, en particular la cámara proporcional multihilo.',
    impact: 'Inventó el detector que reemplazó a las cámaras de burbujas. Sin él, los descubrimientos del LHC no serían posibles.',
    status: 'pending',
  },

  // ═══════════════════════ INFORMACIÓN CUÁNTICA ═══════════════════════
  {
    id: 'phys-2012-wineland-haroche',
    year: 2012,
    laureates: ['Serge Haroche', 'David Wineland'],
    block: 'info-cuantica',
    title: 'Medir un sistema cuántico individual',
    subtitle: 'Por métodos experimentales innovadores que permiten medir y manipular sistemas cuánticos individuales.',
    impact: 'Haroche: contó fotones uno por uno sin destruirlos. Wineland: gobernó iones individuales en una trampa. Base del cómputo cuántico.',
    status: 'pending',
  },
  {
    id: 'phys-2022-bell-tests',
    year: 2022,
    laureates: ['Alain Aspect', 'John Clauser', 'Anton Zeilinger'],
    block: 'info-cuantica',
    title: 'Entrelazamiento y desigualdades de Bell',
    subtitle: 'Por experimentos con fotones entrelazados, que establecen la violación de las desigualdades de Bell y son pioneros en la ciencia de la información cuántica.',
    impact: 'Probaron que el entrelazamiento cuántico es real — el mundo NO es localmente realista. Einstein estaba equivocado en su crítica a la cuántica.',
    status: 'pending',
  },

  // ═══════════════════════ COMPLEJIDAD, CLIMA Y ML ═══════════════════════
  {
    id: 'phys-2021-climate-complex',
    year: 2021,
    laureates: ['Syukuro Manabe', 'Klaus Hasselmann', 'Giorgio Parisi'],
    block: 'complejidad-clima-ml',
    title: 'Sistemas complejos: del clima al vidrio de espín',
    subtitle: 'Manabe y Hasselmann: por modelos físicos del clima terrestre, cuantificando la variabilidad y prediciendo confiablemente el calentamiento global. Parisi: por el descubrimiento de la interacción entre desorden y fluctuaciones en sistemas físicos a escalas atómicas a planetarias.',
    impact: 'Manabe: en 1967 ya predijo el calentamiento por CO₂. Parisi: replica trick — una idea técnica que terminó iluminando redes neuronales y plegamiento de proteínas.',
    status: 'pending',
  },
  {
    id: 'phys-2024-neural-networks',
    year: 2024,
    laureates: ['John Hopfield', 'Geoffrey Hinton'],
    block: 'complejidad-clima-ml',
    title: 'Redes neuronales — el Nobel del machine learning',
    subtitle: 'Por descubrimientos e invenciones fundamentales que permiten el aprendizaje automático con redes neuronales artificiales.',
    impact: 'Hopfield: memoria asociativa como spin glass. Hinton: padrino del deep learning. El Nobel de Física premiando a los inventores de ChatGPT — cambio de era.',
    status: 'pending',
  },
];

/**
 * Cuenta cuántos premios están en cada estado.
 */
export function getPhysicsStats() {
  const total = PHYSICS_CATALOG.length;
  const live = PHYSICS_CATALOG.filter(n => n.status === 'live').length;
  const pending = total - live;
  return { total, live, pending };
}

/**
 * Agrupa los premios por bloque, en el orden definido en PHYSICS_BLOCKS.
 */
export function getPhysicsByBlock(): Array<{ block: PhysicsBlockMeta; entries: PhysicsLaureate[] }> {
  const ordered = [...PHYSICS_BLOCKS].sort((a, b) => a.order - b.order);
  return ordered.map(block => ({
    block,
    entries: PHYSICS_CATALOG
      .filter(n => n.block === block.id)
      .sort((a, b) => a.year - b.year),
  }));
}
