import { cuspHeight, lobeRoughnessAtTilt, precisionFraction, worstOverhangDeg, selfSupports, compareStrategies, envelopeReduction } from '../src/forja/mech/print45';
let pass=0,fail=0; const near=(a,b,t=1e-3)=>Math.abs(a-b)<t; const ck=(n,ok,x='')=>{if(ok)pass++;else{fail++;console.log('✗ '+n+' '+x);}};
ck('cara vertical (90°) → lisa (cusp 0)', cuspHeight(90,0.2)===0);
ck('cara a 45° → cusp 0.707·h ≈ 0.141', near(cuspHeight(45,0.2),0.1414,1e-3));
ck('lóbulo vertical (tilt 0) → liso', lobeRoughnessAtTilt(0,0.2)===0);
ck('lóbulo a 45° tilt → 0.141mm', near(lobeRoughnessAtTilt(45,0.2),0.1414,1e-3));
ck('lóbulo acostado (90°) → 0.2mm (peor)', near(lobeRoughnessAtTilt(90,0.2),0.2,1e-3));
ck('45°: AMBOS auto-soportan', selfSupports(45));
ck('vertical (cic.2 acostado): NO auto-soporta', !selfSupports(0));
ck('precisión a 45°: 0.141/0.7 ≈ 20% del gap', near(precisionFraction(0.1414,0.7),0.202,0.01));
const s=compareStrategies(0.2,0.7);
ck('3 estrategias', s.length===3 && s[0].pieces===2 && s[1].pieces===1);
ck('45° es 1 pieza + auto-soporta', s[1].pieces===1 && s[1].bothSelfSupport);
ck('vertical-1pieza FALLA (cic.2 acostado)', !s[2].bothSelfSupport);
const env=envelopeReduction({cyc1H:30,postH:42,cyc2H:26});
ck('45° reduce el tamaño (anida en diagonal)', env.reductionPct>0 && env.at45_mm<env.upright_mm, JSON.stringify(env));
console.log(`\nPRINT45_TEST pass=${pass} fail=${fail}`);
console.log('estrategias:',JSON.stringify(s,null,1));
console.log('tamaño:',JSON.stringify(env));
process.exit(fail===0?0:1);
