cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(forja_sysbringup C CXX ASM)
set(PICO_BOARD pico2)
pico_sdk_init()
add_executable(forja_sysbringup main.c)
target_link_libraries(forja_sysbringup pico_stdlib hardware_adc)
pico_enable_stdio_usb(forja_sysbringup 1)
pico_enable_stdio_uart(forja_sysbringup 0)
pico_add_extra_outputs(forja_sysbringup)
